### ISSUE TITLE
Enabling neovim in options throws an error

### ISSUE THREAD

**Issue by SenchoPens** [nix-community/home-manager#1577] opened 2020-10-29 20:00 UTC
### Description

Since this [commit](https://github.com/nix-community/home-manager/commit/b5847455066d0191cebd6b140531cc154443e316) executing `nixos-rebuild switch` throws an error:
```
error: --- TypeError ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
at: (151:10) in file: /nix/store/d2h4pc8xx5b3nmsrqjyaxixlzsfqdkcv-source/pkgs/applications/editors/neovim/utils.nix

   150|       wrapperArgs = res.wrapperArgs
   151|       ++ [
      |          ^
   152|         "--add-flags" "-u ${writeText "init.vim" res.neovimRcContent}"

value is the partially applied built-in function 'trace' while a list was expected
(use '--show-trace' to show detailed location information)
```

#### Maintainer CC

@beardhatcode 

#### Steps to reproduce
```
  home-manager.users.sencho.programs.neovim = {
    enable = true;
  };
```
}
#### Technical details

 - system: `0`
 - host os: `Linux 5.9.1, NixOS, 21.03.20201029.f155651 (Okapi)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201029_bb8e837`
 - nixpkgs: `/etc/nixpkgs`

**Comment by berbiche** [comment] 2020-10-30 01:21
@teto ping since git blame is pointing towards your changes to `neovim/utils.nix` on nixpkgs

**Comment by beardhatcode** [comment] 2020-10-30 09:17
I cannot reproduce this issue.

But from what I see, @teto changed the nvim package in the nixpkgs to no longer use extraMakeWrapperArgs as a string. But to use `wrapperArgs` as an array. I do not have time to fix and test this now (I will tomorrow).

**Comment by teto** [comment] 2020-10-30 09:28
wow that was fast, are you using master ? the change doesn't seem to have reached unstable yet ! sorry that it broke your setup, I will try to fix it this evening. 
With those changes, it's now possible for home-manager to write the neovim config directly in $XDG_CONFIG_HOME/nvim/init.vim, thus avoiding issues linked to `-u`. Here is how to do it (I currently write it to `init.generated.vim`)
https://github.com/teto/home-manager/blob/scratch/modules/programs/neovim.nix#L260

**Comment by SenchoPens** [comment] 2020-10-30 10:56
Hi, I use flakes and yesterday tried to update to master. No problem, I have no particular need in the most recent home-manager, I will just use the older revision.

**Comment by colemickens** [comment] 2020-10-30 21:15
This hit `nixos-unstable-small` at least, btw.

**Comment by reedrw** [comment] 2020-11-01 02:29
The build no longer fails but `programs.neovim.vimAlias` seems to no longer work.

**Comment by beardhatcode** [comment] 2020-11-01 09:48
This issue is fixed in nixpkgs (https://github.com/NixOS/nixpkgs/pull/102231) by @teto

**Comment by evalexpr** [comment] 2020-11-02 01:01
@reedrw maybe we should create a new issue for that? I've noticed the same behavior

**Comment by teto** [comment] 2020-11-02 23:27
no need to create another issue: I will have a look at it tomorrow.

**Comment by jonringer** [comment] 2020-11-03 02:24
Should we wrap the application outside of nixpkgs?

There's nothing to guarantee alignment between home-manager and nixpkgs. 

I think it would make sense for nixpkgs to provide a neovim-unwrapped packaged, but if someone were to be using home-manager, then we would probably want to wrap the settings within the context of home-manager.

**Comment by teto** [comment] 2020-11-03 10:44
> I think it would make sense for nixpkgs to provide a neovim-unwrapped packaged

It is already the case, it's even called `neovim-unwrapped`.

> but if someone were to be using home-manager, then we would probably want to wrap the settings within the context of home-manager.

if home-manager generates $XDG_CONFIG_HOME/nvim/init.vim, then we shouldn't need to wrap neovim-unwrapped.

**Comment by reedrw** [comment] 2020-11-03 22:55
Seems like everything is good now. Thanks! 👍

**Closed** 2020-11-03 22:58 UTC
