### ISSUE TITLE
neovim: plugins don't work without extraConfig 

### ISSUE THREAD

**Issue by ethancedwards8** [nix-community/home-manager#1712] opened 2021-01-11 03:54 UTC
### Issue description

When configuring neovim with home-manager if you use the plugins option and run neovim no plugins will work or be loaded at all. If you add an extraConfig option, even when blank, the plugins begin to work.

### Meta
config: 
```nix
  programs.neovim = {
    enable = true;
    viAlias = true;
    vimAlias = true;
    package = pkgs.neovim-nightly;
    # package = pkgs.neovim;
    extraConfig = ''

    '';
  plugins = with pkgs.vimPlugins; [
    fzf-vim
    vim-rooter
    vim-commentary 
    vim-css-color
    vim-fugitive
    # vifm
    lightline-vim #lightline.vim
    vim-highlightedyank
    vim-nix
    vimtex
    nerdtree
    ];

  };
```

#### Maintainer CC

@teto 

#### Technical details

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.2.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixpkgs-21.03pre262503.51894963cbd, darwin, home-manager"`
 - channels(ece): `"darwin, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by berbiche** [comment] 2021-01-11 04:26
Looking at the logic in the neovim module, plugins are automatically started only if `extraConfig` is not empty or any plugins have a configuration.

https://github.com/nix-community/home-manager/blob/cc89be5a30f3a07ba9fbb32ac09b8380d9b99f02/modules/programs/neovim.nix#L53-L66
https://github.com/nix-community/home-manager/blob/cc89be5a30f3a07ba9fbb32ac09b8380d9b99f02/modules/programs/neovim.nix#L247-L253

cc: @teto

**Comment by ethancedwards8** [comment] 2021-01-11 04:45
So would this be considered a bug? @berbiche

**Comment by berbiche** [comment] 2021-01-11 04:49
> So would this be considered a bug? @berbiche 

I believe it does

**Comment by teto** [comment] 2021-01-11 09:27
could be that now that the file is generated in ~/.config/nvim/init.vim it doesn't see the installed plugins. I dont see why adding extraConfig would fix this though. I am a bit busy at the moment so any insight/patch welcome.

**Comment by teto** [comment] 2021-01-29 15:49
@berbiche has spotted the issue: without any global config orplugin-specific config, plugins get ignored. Baiscally `moduleConfigre` should always contain `packages.home-manager` regardless of extraConfig or not.
@ethancedwards8 want to fix ? it's simple enough. Ideally we would improve testing too.

**Comment by teto** [comment] 2021-02-03 22:35
@ethancedwards8  can you check if https://github.com/nix-community/home-manager/pull/1756 solves it for you ?

**Comment by ethancedwards8** [comment] 2021-02-05 22:05
@teto Yup, that pr fixed the issue for me.

**Comment by berbiche** [comment] 2021-02-05 22:13
> Yup, that pr fixed the issue for me.

Closing the issue if the problem is resolved.

**Closed by berbiche** 2021-02-05 22:13 UTC
Labels: bug, program: neovim
