### ISSUE TITLE
bug: installation fails due to python3.10-pyopenssl-22.0.0 being marked as broken on aarch64-darwin

### ISSUE THREAD

**Issue by jost-s** [nix-community/home-manager#3229] opened 2022-09-16 15:46 UTC
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I've recently bought an M1 computer and wanted to install home manager again. Following the instructions from the manual, I run into an error when issuing the command:

```zsh
$ nix-shell '<home-manager>' -A install 

Creating initial Home Manager generation...

error: Package ‘python3.10-pyopenssl-22.0.0’ in /nix/store/rlvm5fc11c2whw6mfb8nnx0hz7c9cp8i-nixpkgs/nixpkgs/pkgs/development/python-modules/pyopenssl/default.nix:73 is marked as broken, refusing to evaluate.

       a) To temporarily allow broken packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_BROKEN=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowBroken = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowBroken = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
Uh oh, the installation failed! Please create an issue at

    https://github.com/nix-community/home-manager/issues

if the error seems to be the fault of Home Manager.
```

When I look at the [Nix package registry](https://search.nixos.org/packages?channel=unstable&show=python310Packages.pyopenssl&from=0&size=50&sort=relevance&type=packages&query=python3.10-pyopenssl), I find the package but only the `x64_64` platform leads to a valid build.

Browsing other M1-related issues here, I never see anyone using the `NIXPKGS_ALLOW_BROKEN` flag for their installations. Is that required or not?

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.5.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixpkgs"`
 - channels(jost): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by dbaynard** [comment] 2022-09-18 22:51
This is an issue with pyopenssl: it doesn't support apple silicon, and it seems like it won't. I'm not :100: on all the details, but there are a series of issues on the nixpkgs tracker itself (the main one is https://github.com/NixOS/nixpkgs/issues/175875).

Unfortunately the workarounds are a little awkward. The best option will probably be to use the `x86_64` versions with rosetta. I've had some success in overriding derivations where pyopenssl is only needed for tests — I don't like this, though.

**Comment by jost-s** [comment] 2022-09-20 15:10
It seems to work if I allow broken packages. But I didn't want to go down the road of relying on an unsupported package for my entire nix package management.

pyopenssl won't support Apple Silicon - mmh, that's a really big bummer. That would mean that there's never a native support of Apple machines while home manager is using pyopenssl.

**Comment by dbaynard** [comment] 2022-09-20 15:21
I have `aarch64-darwin` home-manager running on my M1 mac. I didn't think I'd done anything special, but I do have the following in a `python-overrides.nix` file (to disable tests for packages with a pyopenssl test dependency).

```nix
{ lib
, stdenvNoCC
, ApplicationServices
}:
final: prev:
let

  dontInstallCheck = drv: drv.overrideAttrs (_: {
    doInstallCheck = false;
  });

  darwin = f: drv: if stdenvNoCC.isDarwin then f drv else drv;

in
{
  cheroot = darwin dontInstallCheck prev.cheroot;
  cherrypy = darwin dontInstallCheck prev.cherrypy;

  fonttools = darwin dontInstallCheck prev.fonttools;

  twisted = darwin dontInstallCheck prev.twisted;

  uharfbuzz = prev.uharfbuzz.overridePythonAttrs (old: {
    buildInputs = old.buildInputs or [ ] ++
      lib.optionals stdenvNoCC.isDarwin [ ApplicationServices ];
    meta = old.meta or { } // { broken = false; };
  });
}
```

This is then called with the following, in an overlay.

```nix
  python3 = prev.python3.override {
    packageOverrides = import ./python-overrides.nix {
      inherit (prev) lib stdenvNoCC;
      inherit (prev.pkgs.darwin.apple_sdk.frameworks) ApplicationServices;
    };
  };
```

**Comment by jost-s** [comment] 2022-09-21 14:27
Huh, yes, I guess then that omitting the test saves you from this broken package message, right?

**Comment by dbaynard** [comment] 2022-09-21 14:34
Yes… but more precisely, where it is only the test suite that is broken, not the package, I can just not run the test suite. It's not that I'm hiding the message, I'm not running the broken code.

(The uharfbuzz example I either backported from nixpkgs and can remove, or must push to nixpkgs.)

I don't like not running the tests, but unfortunately it seems the best option.

**Comment by dbaynard** [comment] 2022-09-21 15:12
Basically yes — the package builds but the 'ffi interface' doesn't work, so some downstream packages (dependencies of pyopenssl) will fail. And the cause is that the upstream functionality (as in pyopenssl itself, not the nix packaging) won't support apple silicon.

I think the decision in the issue is the correct one: I'd rather start from the position that 'slightly broken' means 'broken'. But if you know a package is only using parts of pyopenssl that work, by all means mark it unbroken, for your use.

https://github.com/NixOS/nixpkgs/issues/175875#issuecomment-1192606332 seems to be the summary of what was fixed.

> We don't need to keep this none actionable issue open. We removed the biggest pyopenssl usages across the python package set and upstream didn't fix this in the last 3 years and I doubt it will be fixed anytime soon.
> 
> My call is to close this issue because there is nothing we can do here except remove pyopenssl where it is optional.

---

That said, I don't see where anything python-related is being pulled in. I've seen python tooling needed during nix evaluation, and I've seen it needed for things like sphinx, but I don't see how it's being brought in to the closure for home-manager.

**Comment by jost-s** [comment] 2022-09-21 15:20
Alright, that's seems a good enough argument then to allow home manager as broken package and not running the risk of it failing. Thanks for the clarification!

**Comment by dbaynard** [comment] 2022-09-21 15:23
Oh, no, I wasn't arguing for that! I mean, you do you… it's just not obvious to me how home-manager is depending on pyopenssl. And yes, home manager definitely works on M1 macs.

**Comment by jost-s** [comment] 2022-09-21 16:42
cool
I'm fine with closing this issue, as there is no actual solution to this in sight.

**Comment by rycee** [comment] 2022-09-21 21:08
I don't think Home Manager itself depends directly or indirectly on pyopenssl. It is most likely due to some package you are trying to install, e.g., through `home.packages` requiring it?

I'll close this issue since it seem more like a thing for Nixpkgs.

**Closed by rycee** 2022-09-21 21:08 UTC
Labels: bug, triage

**Comment by jost-s** [comment] 2022-09-22 01:19
@rycee 
Aaaahhh, that was it actually!!! I still had a `~/.config/nixpkgs/home.nix` file from the x86_64 Mac. That must have contained some package that depends on pyopenssl.

I backed up that file and ran the installation again and all good!

Thanks for that, no error with home manager after all.
