### ISSUE TITLE
mbsync: multiple channels per account

### ISSUE THREAD

**Issue by znewman01** [nix-community/home-manager#747] opened 2019-07-05 00:26 UTC
Right now, the mbsync `extraConfig.channel` is an attribute set. This is fine when there's only one channel per account. However, in mbsync you often need multiple channels for the same account (e.g. if you want to rename multiple folders). Perhaps some "accounts.email.<account>.mbsync.channels.<channel>" would be more appropriate?

**Comment by rycee** [comment] 2019-07-05 20:45
I see, at the moment the email framework assumes that the folder names are the same on both the remote and local side. It will need some careful consideration to see how this could be supported without breaking too many things in the other email modules 🙂

**Comment by znewman01** [comment] 2019-07-07 15:09
Yeah, I might take a look at it, but I want to OK the plan with you first :)

The problem I'm trying to address is that some part of my email pipeline barfs
on spaces in filenames :( (it's been a while since I set it up, so this may no longer hold).

AFAICT the "folders" for the email is [only used in](https://github.com/rycee/home-manager/search?utf8=%E2%9C%93&q=folders&type=): [mbsync](https://github.com/rycee/home-manager/blob/c3520bfa52b30f984e73e9616abe4d11ab56de36/modules/programs/mbsync.nix#L76) and [astroid](https://github.com/rycee/home-manager/blob/fa3d1f98e001eab0e0514414a6429e082962915a/modules/programs/astroid.nix#L23).
So I think we could:

## Option 1

- define a convention that "folders" is just the local (relative) path to the folders
- rely on configuring the mapping elsewhere (e.g. in mbsync channels) 

I may try to add this at least temporarily if we don't have a better solution
coming.

## Option 2

Extend the `account.folders` from its current state (keys = folder types, values
= folder paths) to something like:

- keys = "folder types" (in practice any name, with some special ones used in
  specific email programs)
- values = EITHER a folder path (for backwards compat) or a { remote = "...", local = "..." }

Then mbsync could be smarter about setting up channels to do the rename for you.

**Comment by teto** [comment] 2019-07-25 10:46
> on spaces in filenames

I would fix this first :D 
I know it's possible to map remote to local folders but I wonder how often it's ever used ? I am not against it but it adds complexity so we should be able to justify it.

**Comment by evanjs** [comment] 2019-08-09 12:40
> > on spaces in filenames
> 
> I would fix this first :D
> I know it's possible to map remote to local folders but I wonder how often it's ever used ? I am not against it but it adds complexity so we should be able to justify it.

Spaces like [these](https://github.com/evanjs/nixos_cfg/compare/a1f58d0cf190cd481efa02ec7a6556a1519acc7a..5259caab84513dc30f97c92a0face9ceb85ecf4b#diff-5c4c9c59c51c70ebc9af9cb376222438L18)?
Looking at my mbsync config and trying to fix it (currently not working with neomutt, I think [this](https://github.com/rycee/home-manager/commit/c3520bfa52b30f984e73e9616abe4d11ab56de36) was the cause, though it was hard to tell what the issue was for a while because spaces just break things.

It'd be nice to be able to map various remote "All mail" folders to ${account}/Inbox locally, anyway.

**Comment by teto** [comment] 2020-01-09 15:29
I hit this issue as well when trying to use Drafts with mbsync/astroid. 
From what I understand, for instance in mbsync, one needs to setup several channels https://gist.github.com/chandraratnam/f00ab7d4a5298830f692021964fdb99f to create the folders.
So I believe we could first update the mbsync code to handle multiple channels (since it will be needed anyway) and then reevaluate the need for more abstraction. 
If HM does too much magic to generate the configuration then it can become bothersome as well.

**Comment by vxid** [comment] 2020-02-14 16:36
Did anyone find a nix-y way to define multiple channels? Right now I'm simply writing my old mbsync configuration to file through nix, but I would like to find a cleaner way to define multiple mbsync accounts.

**Comment by teto** [comment] 2020-05-02 16:46
@znewman01 @vxid note that I know. I don't think we have to abstract this. An adhoc solution should be fine. Seems like cahnnels can be regrouped under a `Group` umbrella if that helps:
https://wiki.archlinux.org/index.php/Isync

**Comment by vxid** [comment] 2020-05-04 11:47
@teto Thanks for your reply. I am already using groups in my `mbsyncrc`, but I don't know if it is sufficient to define multiple email accounts and renaming mailboxes at the same time.

I am using a verbatim config for now, but I have no idea if this could be turned into a "pure" nix configuration given the limitations stated above:

```nix
    home-manager.users.vxid.home.file.".mbsyncrc".text = ''
      Create Both
      Expunge Both
      SyncState *
      Sync All

      IMAPAccount prv
      Host imap.gmail.com
      User user1@private.com
      PassCmd "${pkgs.pass}/bin/pass srv/gmail"
      SSLType IMAPS

      IMAPStore prv-remote
      Account prv

      MaildirStore prv-local
      Subfolders Verbatim
      Path ~/var/mail/prv/
      Inbox ~/var/mail/prv/inbox

      Channel prv-trash
      Master ":prv-remote:[Gmail]/Trash"
      Slave ":prv-local:trash"
      ExpireUnread yes

      Channel prv-inbox
      Master ":prv-remote:INBOX"
      Slave ":prv-local:inbox"

      Channel prv-drafts
      Master ":prv-remote:[Gmail]/Drafts"
      Slave ":prv-local:drafts"

      Channel prv-sent
      Master ":prv-remote:[Gmail]/Sent Mail"
      Slave ":prv-local:sent"

      Channel prv-archive
      Master ":prv-remote:[Gmail]/All Mail"
      Slave ":prv-local:archive"

      Group prv
      Channel prv-sent
      Channel prv-drafts
      Channel prv-trash
      Channel prv-inbox

      IMAPAccount wrk
      Host outlook.office365.com
      Port 993
      User email2@work.com
      PassCmd "${pkgs.pass}/bin/pass wrk/mail"
      SSLType IMAPS

      IMAPStore wrk-remote
      Account wrk

      MaildirStore wrk-local
      Subfolders Verbatim
      Path ~/var/mail/wrk/
      Inbox ~/var/mail/wrk/inbox

      Channel wrk-inbox
      Master ":wrk-remote:INBOX"
      Slave ":wrk-local:inbox"

      Channel wrk-trash
      Master ":wrk-remote:Deleted\ Items"
      Slave ":wrk-local:trash"
      ExpireUnread yes

      Channel wrk-drafts
      Master ":wrk-remote:Drafts"
      Slave ":wrk-local:drafts"

      Channel wrk-sent
      Master ":wrk-remote:Sent\ Items"
      Slave ":wrk-local:sent"

      Channel wrk-archive
      Master ":wrk-remote:Archive"
      Slave ":wrk-local:archive"

      Group wrk
      Channel wrk-inbox
      Channel wrk-trash
      Channel wrk-drafts
      Channel wrk-sent
      Channel wrk-archive
    '';


```

**Comment by teto** [comment] 2020-05-04 13:07
After spending much time on the mail infra, I am not motivated to write the nix code myself but I am willing to test & review if anyone is motivated.

**Comment by vxid** [comment] 2020-05-04 14:43
Fair enough. That may be the occasion for me to learn Nix and give it a go.

**Comment by teto** [comment] 2020-12-04 09:24
I think this was fixed in the linked PR.

**Closed by teto** 2020-12-04 09:24 UTC
Labels: mail
