### ISSUE TITLE
Auto-comment generated config files

### ISSUE THREAD

**Issue by leothelocust** [nix-community/home-manager#3072] opened 2022-07-06 19:27 UTC
### Description
When I use home-manager to generate my config files (for example generating ~/.ssh/config using `programs.ssh`), I would like the ability to prefix the generated file with a comment that says something like:
```conf
# DO NOT EDIT - auto generated by home-manager

...

Host something.net
  User root
```
Is there a way to achieve this across all the generated files easily? or maybe somehow with derivations?

I'm pretty fresh with nix still (day 3) please forgive if silly question.

**Comment by sumnerevans** [comment] 2022-07-06 19:31
They are all already uneditable symlinks into `/nix/store`, so not sure this is necessary... In general, we would have to implement this per-config-type, and some of the config generators are from upstream nixpkgs so they would be annoying to override.

Also, not every config type has comments, either (and they definitely don't all have the same style).

**Comment by rycee** [comment] 2022-07-09 21:39
For what it is worth, some HM modules do inject such a comment. For example, the [mbsync module](https://github.com/nix-community/home-manager/blob/8d5b07fc83d579cd196125e698454b4eb4850646/modules/programs/mbsync.nix#L279-L282) puts

    # Generated by Home Manager.

at the top of the generated configuration file.

IMHO it seems pretty helpful to have such a comment, although I don't feel very strongly about it. Especially, as @sumnerevans says, the file in the Nix store is read-only by design and the symlink will make it pretty clear that it is generated by HM.

If somebody feels like adding such a comment while working on a module I don't mind, but I would avoid a spammy commit that adds such a comment for all configuration files. So since there is nothing actionable here, I'll close this issue.

Oh, and while it is impossible to do something like this across all generated configuration files you can, for the specific case of SSH, add the comment in your own configuration by using the `mkBefore` function:

```
home.file.".ssh/config".text = lib.mkBefore ''
  # DO NOT EDIT - auto generated by home-manager

'';

**Closed by rycee** 2022-07-09 21:39 UTC
Labels: feature request
