### ISSUE TITLE
Offlineimap should use Python 3

### ISSUE THREAD

**Issue by rycee** [nix-community/home-manager#2909] opened 2022-04-24 07:52 UTC
### Description

Currently the offlineimap module depends on Python 2 but it seems like the [offlineimap package in Nixpkgs](https://github.com/NixOS/nixpkgs/blob/347647008b6366890bf013aa3098a50f4faeffc4/pkgs/tools/networking/offlineimap/default.nix) has switched to Python 3. Perhaps it would be possible to also switch in the HM module?

@teto could you help with this?

**Comment by teto** [comment] 2022-04-24 16:05
not sure what I can do ? bumping nixpkgs should be enough, shouldn't it ?

**Comment by rycee** [comment] 2022-04-24 20:20
The module refers specifically to Python 2:
https://github.com/nix-community/home-manager/blob/65a32578d9b1394bea5c6336721ec392aadc89fb/modules/programs/offlineimap.nix#L161

I imagine it may be sufficient to simply switch it over to Python 3? Maybe with an entry in the release notes saying that the module now expects Python 3 for that script.

**Comment by teto** [comment] 2022-04-24 21:38
my bad I missed it, this line is from @markusscherer  I now use mbsync

**Comment by markusscherer** [comment] 2022-04-25 09:31
Hi!

If I remember correctly, I added the dependency to be able to precompile the `get_settings.py` file here since changes to this file via `home-manager` would not be loaded if a compiled version of the file was already there and not tracked by `home-manager`.

 https://github.com/nix-community/home-manager/blob/09f3e67950823d5abe192e474f1af51914f4cb9a/modules/programs/offlineimap.nix#L167

I'm not a python specialist, but I assume something similar would be possible in `python3`.

My particular use-case for overriding the default `get_settings.py` was by the way addressed shortly after I committed my changes in https://github.com/nix-community/home-manager/commit/040ea28e448a93d24540b7cf2eda4b25300c5ab1.

**Comment by teto** [comment] 2022-04-25 09:50
the scenario is valid, the problem is just that instead of hardcoding python2, we would need to use the same python as offlineimap's. I dont know of any robust way to do that so we should probably hardcode it. (would be nice if we could get the python environment from a package passhtrough).

**Comment by markusscherer** [comment] 2022-04-25 19:36
It seems we are lucky: I just replaced `pkgs.python2` in `buildInputs` with `pkgs.offlineimap` and the invocation of `python2` with `python` and the whole thing still works. If I understand `nix` correctly, this is because `offlineimap` has the python-package it uses in `propagatedBuildInputs`.

**Comment by teto** [comment] 2022-05-17 09:32
should be fixed in https://github.com/nix-community/home-manager/pull/2951

**Closed by teto** 2022-05-17 09:32 UTC
Labels: feature request
