### ISSUE TITLE
Make nushell use home.sessionVariables

### ISSUE THREAD

**Issue by RGBCube** [nix-community/home-manager#4739] opened 2023-12-05 17:06 UTC
@Philipp-M 

Nushell does not load /etc/profile or the local profile, so it is unaware of `environment.variables`, `environment.sessionVariables` (not sure whats the difference between the 2) and `home.sessionVariables` entirely. This breaks stuff like `programs.helix.defaultEditor`. Could you make it so it uses them by default?

**Comment by Philipp-M** [comment] 2023-12-05 18:27
I'm currently not using nushell. But I'm happy to review a PR implementing this.

As a workaround for now, it shouldn't be too hard though to inject the `home.sessionVariables` via [`programs.nushell.environmentVariables`](https://nix-community.github.io/home-manager/options.html#opt-programs.nushell.environmentVariables)

**Comment by alecandido** [comment] 2024-05-11 10:41
> As a workaround for now, it shouldn't be too hard though to inject the `home.sessionVariables` via [`programs.nushell.environmentVariables`](https://nix-community.github.io/home-manager/options.html#opt-programs.nushell.environmentVariables)

The workaround works perfectly.

Is there any drawback to implement exactly like this in the module? (i.e. appending/prepending in the exact same place where `programs.nushell.environmentVariables` is used)

https://github.com/nix-community/home-manager/blob/d7682620185f213df384c363288093b486b2883f/modules/programs/nushell.nix#L176-L177

**Comment by Philipp-M** [comment] 2024-05-11 11:39
Hmm at least when doing this automatically, one drawback would be that the `envFile` would be created automatically, not sure how good this behavior is (e.g. when for whatever reason that file would be managed manually). There could be a boolean option though to toggle this behavior (maybe as default = set the `sessionVariables`?).

**Comment by alecandido** [comment] 2024-05-11 18:00
What if we make it opt-out?

I believe the most sensible default, for someone who is unfamiliar with Nushell, or just trying it, would be to get the `sessionVariables` as in the other shells.
Then, if you really want to manually manage your `envFile` (which I would assume is not that common, for people using home manager), you could entirely disable its generation.

Eventually, even for all the other shells some files have to be managed by home-manager in order to get `sessionVariables`, even if they are sourced from an external file (once any modification is needed, the whole file becomes managed).

It's also possible to do exactly like in the other shells, by writing the `sessionVariables` in a standalone file, and just source it in `env.nu`. But I'm not sure I see the advantage of this approach, even in the case of Bash & co. (though just doing it for consistency would be nice...).

**Comment by Philipp-M** [comment] 2024-05-12 11:06
> What if we make it opt-out?

Sure as I said:

> But I'm happy to review a PR implementing this.

> (maybe as default = set the `sessionVariables`)

I just don't have time currently to do this myself.

> by writing the sessionVariables in a standalone file, and just source it in `env.nu`

I don't see a benefit in it, when we still need to write the `env.nu`, it would make sense, if (not sure, maybe it's even supported) nushell would source a directory of env scripts without having to specify it in `env.nu`, but if not, we can just directly generate it into that file...

**Comment by alecandido** [comment] 2024-05-12 11:15
> I just don't have time currently to do this myself.

I was considering doing it myself, not requesting someone else. For the time being, I'm fine with the workaround in my configuration, it's not an urgent need. But as soon as I have to repeat it somewhere else, I'd rather write a PR.

I was just gathering opinions about how to do it :)

> I don't see a benefit in it, when we still need to write the `env.nu`, it would make sense, if (not sure, maybe it's even supported) nushell would source a directory of env scripts without having to specify it in `env.nu`, but if not, we can just directly generate it into that file...

That was my perspective as well. But it should be the same for Bash, and yet
https://github.com/nix-community/home-manager/blob/44677a1c96810a8e8c4ffaeaad10c842402647c1/modules/home-environment.nix#L569-L570

I guess the reason is that you can have home-manager without having it to manage your shell
https://github.com/nix-community/home-manager/blob/44677a1c96810a8e8c4ffaeaad10c842402647c1/docs/manual/installation/standalone.md?plain=1#L39-L44

Wouldn't that apply in the exact same way even to Nushell? Or am I missing something?

**Comment by Philipp-M** [comment] 2024-05-13 16:41
Hmm I would need to check that as well (and at that point I could probably also implement that PR), but orienting among the other shells, seems like a good idea? From a quick look, I would check the content of `sessionVariablesPackage` and use that as a base. I do think the `sessionVariablesPackage` is used for a few programs (or to be precise `fish` it seems), so that's probably the reason it's done like that.

**Comment by alecandido** [comment] 2024-05-13 16:57
Not sure how simple is to parse that file, since just *evaluating* it should not be possible with Nu...

I believe the easiest would be to source the file with Bash in a script, and then output `env` (possibly unsetting all variables before, to isolate `sessionVariablesPackage` definitions...).
However, if there is anything like `export PATH=$PATH:/path/to/my/bins/` I'm not sure at all if there is anything simpler than parsing it and convert...

Maybe I'm a bit catastrophic, but I assumed that directly using `sessionVariablesPackage` was not a viable option because of the incompatible syntax. Maybe it is, and I simply don't know how.

**Comment by Philipp-M** [comment] 2024-05-13 17:03
Honestly I'm a bit out of the loop regarding nushell, I would probably investigate how nushell handles all of this (including `PATH`) etc. and if there's a general recommended way to handle all of this...

**Comment by alecandido** [comment] 2024-05-13 17:54
https://www.nushell.sh/book/configuration.html#nushell-configuration-with-env-nu-and-config-nu
https://www.nushell.sh/book/configuration.html#path-configuration

But, as I said, I could do it myself. I simply didn't want to start until I had a decent understanding about how it is done in other cases...

**Comment by quazar-omega** [comment] 2024-06-02 20:35
Just checking in, isn't this a duplicate of #4313?

**Comment by sumnerevans** [comment] 2024-06-04 03:49
Duplicate of #4313. Closing.

**Closed by sumnerevans** 2024-06-04 03:49 UTC
Labels: feature request
