### ISSUE TITLE
Installing home-manager fails with "error: attribute 'anything' missing"

### ISSUE THREAD

**Issue by PoignardAzur** [nix-community/home-manager#2072] opened 2021-06-05 13:59 UTC
### Issue description

I've tried to install home-manager, following the instructions in the README.

When I run the following command:

```sh
> nix-shell '<home-manager>' -A install --show-trace
```

I get the following result:

```sh
Creating initial Home Manager generation...

error: attribute 'anything' missing, at /nix/store/ncd2gsy5wdngxk4bi458lg1da8hg191b-home-manager/home-manager/modules/programs/matplotlib.nix:26:28
(use '--show-trace' to show detailed location information)

There are 153 unread and relevant news items.
Read them by running the command 'home-manager news'.

Uh oh, the installation failed! Please create an issue at

    https://github.com/nix-community/home-manager/issues

if the error seems to be the fault of Home Manager.
```

#### Maintainer CC

I'm not sure who to ping.

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.108, NixOS, 20.09.3684.9cea2bf89b5 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(olivier-faure): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sumnerevans** [comment] 2021-06-05 14:17
@rprospero since he's the maintainer of the `matplotlib` module.

**Comment by rprospero** [comment] 2021-06-05 14:29
@PoignardAzur The good news is that I've encountered this problem before and there's a work-around.  The other good news is that it's not your fault.  The bad news is that I don't *quite* remember how I got around this the last time.  I'll take a look at it again on Monday and do a proper write-up of the solution.

If you're in a really time critical situation at the moment, you should be able to commend out the matplotlib part of your config and compile the rest of your config.

**Comment by PoignardAzur** [comment] 2021-06-05 14:33
Not time-critical, just exploring NixOS. Thank you for your prompt answer.

**Comment by cole-h** [comment] 2021-06-05 15:59
Duplicate of https://github.com/nix-community/home-manager/issues/1665, probably.

**Comment by rycee** [comment] 2021-06-05 17:42
Yes, @PoignardAzur you are using the master (or release-21.05) branch of HM with version 20.09 of NixOS. This does not work, you need to either use the release-20.09 branch of HM or, better, upgrade your system to 21.05 and use the release-21.05 branch.

**Closed by rycee** 2021-06-05 17:42 UTC

**Comment by PoignardAzur** [comment] 2021-06-05 17:54
I feel like there should be an error message in the install process for this exact case.
