### ISSUE TITLE
neovim: fails to build due to failed assertions

### ISSUE THREAD

**Issue by pinpox** [nix-community/home-manager#1813] opened 2021-02-18 15:25 UTC
### Issue description

Using `programs.neovim` is failing to build for me with the following error:

```
error: --- ThrownError --- nix
Failed assertions:
- pinpox profile: The programs.neovim option configure is mutually exclusive with extraConfig and plugins.
```

I'm **only** setting the `configure` option, not any of `plugins` or `extraConfig`. The full configuration related to neovim is here:
https://github.com/pinpox/nixos-home/blob/ab21f70e0e7eda882004b7aae1b7ff1ad7171d6d/modules/vim.nix#L13

#### Maintainer CC
@teto @rycee 

#### Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.94, NixOS, 21.03.20210203.7cbec40 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `""`
 - channels(pinpox): `"home-manager"`
 - nixpkgs: `/nix/store/r52bwmn85n4k1g5xgny3v7acjqfb8spb-source`

**Comment by teto** [comment] 2021-02-18 17:13
duplicate of https://github.com/nix-community/home-manager/issues/1806

**Closed by teto** 2021-02-18 17:13 UTC
