### ISSUE TITLE
Removing files from the nix store

### ISSUE THREAD

**Issue by broccoli5** [nix-community/home-manager#2657] opened 2022-01-21 19:58 UTC
First: Sorry for technically using the wrong template, you guys should really have one for questions too (IMO).

I'm on NixOS 21.11 and I'm using the NixOS Module

So here is my issue: I wanted to get some syntax highlighting working in NeoVim before I copy over my config. So I added this to my `configuration.nix`:

```nix
#...
  programs = {
    # ...
    neovim = {
      enable = true;
      extraConfig = ''
        syntax on
      '';
      plugins = with pkgs.vimPlugins; [
        vim-nix
      ];
    };
    # ...
  };
#...
```

Now that I copied over my config I wanted to add it with `xdg.configFile.nvim.source = ./nvim`, but I get a error that the generated config, which lives in `/nix/store`, is in the way. How do I get rid of it?

I did remove this config and ran `nixos-rebuild switch`, I also tried running the garbage collection but that didn't get rid of it either.

**Comment by berbiche** [comment] 2022-01-21 20:10
> Now that I copied over my config I wanted to add it with `xdg.configFile.nvim.source = ./nvim`, but I get a error that the generated config, which lives in `/nix/store`, is in the way. How do I get rid of it?

I think the error message might be erroneous. If you could share the error message it would help.

Now, I think the real issue is that you are trying to copy your entire neovim configuration over the configuration that Home Manager is generating.

The `programs.neovim.extraConfig` and `.plugins` option will cause the file `$XDG_CONFIG_HOME/nvim/init.vim` to be created.
It creates this file using the same option you use: `xdg.configFile."nvim/init.vim"`.

The issue is that Home Manager cannot merge the conflicting `xdg.configFile."nvim"` with `xdg.configFile."nvim/init.vim"`. The former has precedence over the latter.

You have a few options to solve the issue:
1. Try to add `xdg.configFile.nvim.recurse = true;`, it will recursively copy the source, allowing you to add other files in `$XDG_CONFIG_HOME/nvim`.
2. Copy each item individually with `xdg.configFile."nvim/some-file.vim".source = ./nvim/some-file.vim`
3. Move your entire vim/lua configuration to Home Manager

> Sorry for technically using the wrong template, you guys should really have one for questions too (IMO).

Tracked here: https://github.com/nix-community/home-manager/issues/2525

**Comment by broccoli5** [comment] 2022-01-21 20:24
Here is the error message:

```
Jan 21 21:15:05 t410 hm-activate-broccoli[9350]: cmp: /nix/store/f04za9nhps1iciwiqna9wihkrhxximss-home-manager-files/.config/nvim: Is a directory
Jan 21 21:15:05 t410 hm-activate-broccoli[9344]: Existing file '/home/broccoli/.config/nvim' is in the way of '/nix/store/f04za9nhps1iciwiqna9wihkrhxximss-home-manager-files/.config/nvim'
Jan 21 21:15:05 t410 hm-activate-broccoli[9344]: Please move the above files and try again or use 'home-manager switch -b backup' to back up existing files automatically.
Jan 21 21:15:05 t410 systemd[1]: home-manager-broccoli.service: Main process exited, code=exited, status=1/FAILURE
Jan 21 21:15:05 t410 systemd[1]: home-manager-broccoli.service: Failed with result 'exit-code'.
Jan 21 21:15:05 t410 systemd[1]: Failed to start Home Manager environment for broccoli.
Jan 21 21:15:05 t410 systemd[1]: home-manager-broccoli.service: Consumed 113ms CPU time, received 368B IP traffic, sent 412B IP traffic.
warning: error(s) occurred while switching to the new configuration
```

(I did try deleting the symlink in my home directory, but I still got this error.)

This is the current config I'm trying to use:

```nix
  #...
      programs = {
        neovim = {
          enable = true;
          viAlias = true;
          vimAlias = true;
        };
      };
 
      xdg.configFile = {
        nvim.source = ./nvim;
      };
  #...
```

I found out that I can use `builtins.readFile` with `extraConfig` to get around this issue, but it feels bit hacky

**Comment by broccoli5** [comment] 2022-01-21 20:40
> 1. Try to add `xdg.configFile.nvim.recurse = true;`, it will recursively copy the source, allowing you to add other files in `$XDG_CONFIG_HOME/nvim`.

Just to confirm, this also works, I made the previous comment before trying it

**Comment by berbiche** [comment] 2022-01-21 20:59
Feel free to close this issue if the problem is resolved.

**Closed** 2022-01-21 21:14 UTC
Labels: question
