### ISSUE TITLE
xmonad recompilation makes `home-manager switch` fail

### ISSUE THREAD

**Issue by dnaq** [nix-community/home-manager#1895] opened 2021-04-01 06:29 UTC
I was going to post this, but I found the following comment on a different issue that explains the problem.

> Somewhat related, more of a warning. If you have a xmonad configuration that includes a binding for both recompiling and restarting xmonad, it will override the nix managed xmonad symlink with the new binary. This will cause later nix rebuilds to fail because the file already exists.

> _Originally posted by @MasseR in https://github.com/nix-community/home-manager/issues/1891#issuecomment-810014778_

**Comment by markusscherer** [comment] 2021-04-02 17:27
This is something I also noticed while rewriting the xmonad build (https://github.com/nix-community/home-manager/pull/1765#issuecomment-787433076 and following comments). One alternative would be not linking the the config in `$HOME/.xmonad`, this would mean that `xmonad --recompile` would fail (because it does not find `xmonad.hs` etc.).

I don't have a preference. Do you think having a failing `xmonad --recompile` is preferable to a failing `home-manager switch`? Or do you have another solution?

**Comment by dnaq** [comment] 2021-04-02 17:42
I think it’s better to let `xmonad —recompile` fail, since even if it succeeds it should never have an observable effect, and without changing the default keybindings it’s pretty easy to manage to recompile xmonad and thus breaking the next `home-manager switch`. Maybe even better would be to patch out the recompilation stuff from xmonad completely for the home-manager build, but that is of course more work.

**Comment by berbiche** [comment] 2021-04-07 19:22
With #1893 merged, the config file is now optional and can be symlinked directly with `home.file` or `xdg.configFile`

**Comment by berbiche** [comment] 2021-04-09 04:37
@dnaq can this be closed?

**Comment by dnaq** [comment] 2021-04-09 04:41
I would say that those are two orthogonal issues. I think a lot of people
want their config managed by home-manager but will be surprised if they
restart xmonad with the default key binding which also will recompile it
and run into this behavior.

It might be solved with documenting that fact though.

**Comment by markusscherer** [comment] 2021-04-09 08:07
I agree with @dnaq that the issue is orthogonal. It could be solved by removing

```nix
      home.file.".xmonad/xmonad.hs".source = cfg.config;
```
and

```nix
    {
      home.file = mapAttrs' (name: value:
        attrsets.nameValuePair (".xmonad/lib/" + name) { source = value; })
        cfg.libFiles;
    }
``` 

from `modules/services/window-managers/xmonad.nix`.

The problem then is, that if one would recompile xmonad (either via the shortcut or via `xmonad --recompile`) they would encounter an error (otherwise they would encounter the error on `home-manager switch` which might be more confusing, since it's decoupled from the action that caused the error).

(I would issue issue a pull request, but currently I don't have access to my home-manager-managed computer. If they pull request can wait a few days, I could of course do it then).

**Comment by markusscherer** [comment] 2021-04-10 19:01
I removed the files from home and documented the new behavior, which at least mitigates the problem somewhat.

**Comment by woffs** [comment] 2021-05-13 11:23
mod-q is by default bound to recompile and will clash with the new home-manager behaviour. https://github.com/xmonad/xmonad/blob/46f637e0bed18fa09e46e8f8ad5ccd0ae19d6fa0/src/XMonad/Config.hs#L222
It should be documented that this breaks mod-q in the standard configuration.

**Closed** 2021-06-23 00:36 UTC
Labels: bug
