### ISSUE TITLE
Can't install NixOs and Home Manager with flake error access to /mnt/nix/store/<hash>-nmd source/flake.nix is forbidden in restricted mode

### ISSUE THREAD

**Issue by mudrii** [nix-community/home-manager#2074] opened 2021-06-05 14:53 UTC
#### Try to install NisOs with flakes.

Flake.nix configuration

```
{
  description = "NixOS configuration";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-21.05";
    nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { home-manager, nixpkgs, nixpkgs-unstable, ... }: {
    nixosConfigurations = {
      nixtst = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          ./configuration.nix
          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.mudrii = import ./users/mudrii/home.nix;
          }
        ];
      };
    };
  };
}
```

Error during installation 

```
/mnt/nix/store/<hash>-nmd source/flake.nix is forbidden in restricted mode
```

The issue seems to be related to nmd package requirements.

The workaround is to comment out HM configuration in flake.nix and redeploy post instrall.

**Comment by robertoschwald** [comment] 2021-06-09 20:19
Same here. If re-starting installation, it works the 2nd time.

**Comment by berbiche** [comment] 2021-06-17 01:20
I don't have the setup to reproduce the issue, can you point the `home-manager` input to your fork and update this line:

https://github.com/nix-community/home-manager/blob/db00b39a9abec04245486a01b236b8d9734c9ad0/doc/default.nix#L16

to 

```nix
nmd = import (/. + nmdSrc) { inherit lib pkgs; }; 
```

just to see if it resolves the issue?

**Comment by kristoff3r** [comment] 2021-08-24 12:09
I hit the same issue and tried that fix, but that gave the following error:

```
error: a string that refers to a store path cannot be appended to a path
```

Maybe we can somehow prevent the doc module from being evaluated when importing home-manager via flakes? Otherwise I'm not sure how to fix this while still supporting both flake and non-flake installs.

**Comment by Mazurel** [comment] 2021-08-31 09:14
The best workaround for this problem is to use `--impure` flag when installing, this will result with correct installation, at least from my tests.

It seems like it is a `fetchFromGitLab` issue, as the path should be in `allowedPaths` and it looks like it is not for some reason.

**Comment by lordcirth** [comment] 2021-09-13 22:46
Ran into this yesterday. Just tried `nixos-rebuild dry-build --impure` and it didn't change anything. Am I doing it wrong? 21.05 on aarch64. Thanks.

**Comment by Mazurel** [comment] 2021-09-14 21:28
@lordcirth Do you mean `nixos-install --impure --flake ...` ? 

Actually, either way it should work as `--impure` should disable all restricted mode issues. I was installing my system about two weeks ago and `--impure` worked fine, but maybe there were some new changes to Nix in the meanwhile.

**Comment by chayward1** [comment] 2021-09-19 14:15
@Mazurel Thanks for that, I was also running into this issue. It seems the `--impure` flag MUST come before the `--flake ...` flag or you will get the same issue. That solved this for me!

**Comment by berbiche** [comment] 2021-12-27 23:07
@rycee recently made some changes related to nmd. The bug needs to be reinvestigated.

**Comment by t184256** [comment] 2022-07-18 20:30
Still relevant. Please supply this nmd thing as a flake so that I can build my configuration on Hydra.

**Comment by piperswe** [comment] 2022-08-29 22:24
Yep, commit 9550595 breaks home-manager in restricted mode, which breaks evaluation in Hydra. This is a somewhat major issue for me, so I'll be using 0434f8e until this is fixed.

**Comment by patchhoernchen** [comment] 2023-05-02 23:33
I'm also experiencing that issue while trying to build with hydra:
```
error: access to URI 'https://git.sr.ht/~rycee/nmd/archive/abb15317ebd17e5a0a7dd105e2ce52f2700185a8.tar.gz' is forbidden in restricted mode
```

current `flake.lock` from home-manager:
```
    "home-manager": {
      "inputs": {
        "nixpkgs": [
          "nixpkgs"
        ]
      },
      "locked": {
        "lastModified": 1682977601,
        "narHash": "sha256-F1Va/Uiw2tVNn27FLqWyBkiqDyIm/eCamw9wA/GK8Fw=",
        "owner": "nix-community",
        "repo": "home-manager",
        "rev": "0e4c33d76006c9080d2f228ba1c2308e3e4d7be6",
        "type": "github"
      },
      "original": {
        "owner": "nix-community",
        "repo": "home-manager",
        "type": "github"
      }
```

The pull happend from `docs/default.nix:8-12`:
```
  nmdSrc = fetchTarball {
    url =
      "https://git.sr.ht/~rycee/nmd/archive/abb15317ebd17e5a0a7dd105e2ce52f2700185a8.tar.gz";
    sha256 = "0zzrbjxf15hada279irif7s3sb8vs95jn4y4f8694as0j739gd1m";
  };
```

Besides not beeing part of the input for the flake it still looks like a full-qualified fetch to me, but i'm not profecient enough with nix, flakes and (im)purity.

Besides, when building the system-flake locally i don't have that issue.

**Comment by spacekitteh** [comment] 2023-10-16 03:47
Still relevant. Can't run my configs on my Hydra install because of this.

**Comment by victormignot** [comment] 2023-11-15 21:08
@spacekitteh Same here. Unable to build my NixOS configurations (at least the ones using Home Manager) with Hydra.

**Comment by rycee** [comment] 2024-01-17 21:56
I'm pretty certain this is finally fixed with the recent introduction of nmd as a package in Nixpkgs. I'll close the issue, please comment if you think the issue still remains.

**Closed** 2024-01-17 21:57 UTC
Labels: question
