### ISSUE TITLE
`tput` fails for `termite` (its `terminfo` isn't registered?)

### ISSUE THREAD

**Issue by sboosali** [nix-community/home-manager#423] opened 2018-10-18 03:10 UTC
`tput` fails for `termite` with:

```
tput: unknown terminal "xterm-termite"
```

But `tput` works for other terminals, like the default terminal whose `$TERM` is `xterm-256color`. Which makes sense, because it's in `/lib/terminfo/`, the default `$TERMINFO` database distributed:

```
/lib/terminfo/x/xterm-256color
```

I'm on Ubuntu 16.04 under KDE Plasma 5, and my `home.nix` includes

* `bash`:

```nix
programs.bash.enable = true;
programs.bash.bashrcExtra = ''
tput ...
'';
```

* `termite`:

```nix
programs.termite.enable = true;
'';
```

* and has `home-manager` version:

```nix
programs.home-manager = {
  enable = true;
  path = https://github.com/rycee/home-manager/archive/release-18.03.tar.gz;
};
```

I don't know how `home-manager` works, as after exploring `home-manager-generation:

```sh
$ home-manager generations
... -> /nix/store/bm8gyd8lbxyshqdnyv15kbxvyd42v921-home-manager-generation

$ cd /nix/store/bm8gyd8lbxyshqdnyv15kbxvyd42v921-home-manager-generation

$ find -L . -type f | grep -I terminfo
./home-path/share/terminfo/x/xterm-termite
```

I'm stuck on how to properly "register" this. 

Assuming `terminfo.enable` doesn't register `.../share/terminfo/x/xterm-termite` on non-NixOS? Or if it does, and the rest of my config intereferes somehow (though `tput` still fails even with no extra `.bashrc`).

Finally, I could manually link the `share/terminfo` from `nix`:

```sh
/home/sboo/.nix-profile/share/terminfo/x/xterm-termite
```

into the outside-the-home path `/lib/terminfo` (but only if I've got to).

My current workaround is adding the `nix`-generated `terminfo` database to (the otherwise empty) `$TERMINFO_DIRS`:

```nix

```

from my `.bashrc`. like so:

```nix
programs.bash.bashrcExtra =
  ''
  export TERMINFO_DIRS="$HOME/.nix-profile/share/terminfo":/lib/terminfo
  '';
```

Since I don't know how any of these systems actually interact (or even what level they're on), I don't know if this is the right way to do this, or not. 

So, my question is if there's more general solution (like for all standard subdirectories of  `~/.nix-profile/share/`) that `home-manager` provides. And if there isn't, can we add this to the wiki (?), or to the <https://rycee.gitlab.io/home-manager/options.html> (under each support terminal program, like `programs.termite`)?

Thanks.

Links:

* <https://invisible-island.net/ncurses/man/ncurses.3x.html#h3-TERMINFO>
* <https://linux.die.net/man/5/terminfo>

**Comment by dtzWill** [comment] 2018-10-18 13:31
On Wed, 17 Oct 2018 20:10:25 -0700, Spiros Boosalis <notifications@github.com> wrote:
> 
> `tput` fails for `termite` with:
> 
> ```
> tput: unknown terminal "xterm-termite"
> ```
> 
> But `tput` works for other terminals, like the default terminal whose `$TERM` is `xterm-256color`. Which makes sense, because it's in `/lib/terminfo/`, the default `$TERMINFO` database distributed:
> 
> ```
> /lib/terminfo/x/xterm-256color
> ```
> 

FWIW this is often built from the
[terminal db sources](https://invisible-island.net/ncurses/ncurses.html#download_database)
along with ncurses-- which only included an entry for termite
somewhat recently, I'm not sure if it's in Ubuntu 16.04.

Even so it's under the name 'termite' (as in `TERM=termite`) which is
apparently correct but not what termite itself will ever set unless you
patch it (there's an upstream PR for this I believe?).

Basically, terminfo can be a smidge of a pain when using termite :).

The two terminfo entries are not the same (!) and I've never compared
them in detail-- I'm not sure either is entirely appropriate when using
newer VTE.  I'd be interested in more information on this if anyone has
it, for any vte-based terminals or even differences between them :).

--------------------

More helpfully perhaps:

* Does home-manager install `termite.terminfo`? If not it should and
  that's an easy fix I imagine.

* If it does then the question is why isn't it being found,
  at least by `tput` here.  Do other programs successfully work with
  termite? The environment variable `TERMINFO_DIRS` should be set
  to include your nix profile, I forget what bits are responsible for
  that but it's easy to check what your $TERMINFO_DIRS ends up as :).

* Different ncurses versions compile terminfo into incompatible
formats (and build options make this worse IIRC) where programs
using older ncurses can't (necessarily) read terminfo db compiled
by newer ncurses.  Again, yay things can be a bit painful ;).
But basically it might be worth checking where `tput` is coming from
to ensure it's compatible with whatever terminfo db ends up
having the entry for termite.

> I'm on Ubuntu 16.04 under KDE Plasma 5, and my `home.nix` includes
> 
> * `bash`:
> 
> ```nix
> programs.bash.enable = true;
> programs.bash.bashrcExtra = ''
> tput ...
> '';
> ```
> 
> * `termite`:
> 
> ```nix
> programs.termite.enable = true;
> '';
> ```
> 
> * and has `home-manager` version:
> 
> ```nix
> programs.home-manager = {
>   enable = true;
>   path = https://github.com/rycee/home-manager/archive/release-18.03.tar.gz;
> };
> ```
> 
> I don't know how `home-manager` works, as after exploring `home-manager-generation:
> 
> ```sh
> $ home-manager generations
> ... -> /nix/store/bm8gyd8lbxyshqdnyv15kbxvyd42v921-home-manager-generation
> 
> $ cd /nix/store/bm8gyd8lbxyshqdnyv15kbxvyd42v921-home-manager-generation
> 
> $ find -L . -type f | grep -I terminfo
> ./home-path/share/terminfo/x/xterm-termite
> ```
> 
> I'm stuck on how to properly "register" this. 
> 
> Assuming `terminfo.enable` doesn't register `.../share/terminfo/x/xterm-termite` on non-NixOS? Or if it does, and the rest of my config intereferes somehow (though `tput` still fails even with no extra `.bashrc`).
> 
> Finally, I could manually link the `share/terminfo` from `nix`:
> 
> ```sh
> /home/sboo/.nix-profile/share/terminfo/x/xterm-termite
> ```
> 
> into the outside-the-home path `/lib/terminfo` (but only if I've got to).
> 
> My current workaround is adding the `nix`-generated `terminfo` database to (the otherwise empty) `$TERMINFO_DIRS`:
> 
> ```nix
> 
> ```
> 
> from my `.bashrc`. like so:
> 
> ```nix
> programs.bash.bashrcExtra =
>   ''
>   export TERMINFO_DIRS="$HOME/.nix-profile/share/terminfo":/lib/terminfo
>   '';
> ```

Welp looks like I info-dumped without finishing reading your report,
sorry about thiat.  Hope some of it's helpful anyway.

Offhand I think the issue is just that nothing sets TERMINFO_DIRS
when using nix on non-NixOS -- unsure if home-manager should implement
this or if it's something that belongs in
`~/.nix-profile/etc/profile.d/nix.sh` or whatever.
I'd guess concerns about the sort of compatibility problems I mentioned
above are the reason it's not set, but worth investigating further.

(...brainstorming possible causes...)

Or maybe the problem is that the system default is searched when
`TERMINFO_DIRS` if unset but isn't used otherwise; this sort of problem
is often handled by allowing a special '::' (empty) entry to indicate
the default path (so you can do
`TERMINFO_DIRS=$HOME/.nix-profile/share/terminfo::`)... but maybe that's
not supported.

For something like home-manager I'd say if nothing else this makes sense
to have as an opt-in (or opt-out, on by default) feature.

> 
> Since I don't know how any of these systems actually interact (or even what level they're on), I don't know if this is the right way to do this, or not. 
> 
> So, my question is if there's more general solution (like for all standard subdirectories of  `~/.nix-profile/share/`) that `home-manager` provides. And if there isn't, can we add this to the wiki (?), or to the <https://rycee.gitlab.io/home-manager/options.html> (under each support terminal program, like `programs.termite`)?

:<3:

> 
> Thanks.
> 
> Links:
> 
> * <https://invisible-island.net/ncurses/man/ncurses.3x.html#h3-TERMINFO>
> * <https://linux.die.net/man/5/terminfo>
> 

Sorry again for re-sharing information you already knew, I've just spent
a bunch of time chasing down the same sort of thing and wanted to help
:).

"Maybe the hours spent learning these things won't be a waste if it helps
someone..."

:innocent: ;)

**Comment by toonn** [comment] 2019-07-28 17:10
I think I'm running into the same problem with kitty. `infocmp` has no problem finding the `xterm-kitty` terminfo though.
Only way I can get my home-manager configuration activated is using `env TERM=xterm-256color`.

**Comment by SuperSandro2000** [comment] 2020-10-01 21:04
Bump. This makes kitty basically impossible to use with home-manager on non NixOS systems.

**Comment by SuperSandro2000** [comment] 2020-10-01 21:13
For anyone stumbling upon this issue:

This is probably what you are searching for:

```
export TERMINFO_DIRS=$(nix eval --raw nixpkgs.kitty.terminfo.outPath)/share/terminfo
```

**Comment by SuperSandro2000** [comment] 2020-10-02 06:33
Or even better you can do the following in your home.nix:

```
home.sessionVariables = {
  TERMINFO_DIRS = "${pkgs.kitty.terminfo.outPath}/share/terminfo";                                                                                                                                             
};
```

**Comment by aergonaut** [comment] 2020-12-19 00:28
I am also seeing this issue when using kitty, home-manager, and nix-darwin.

I have tried setting `TERMINFO_DIRS` like @SuperSandro2000 [suggested](https://github.com/nix-community/home-manager/issues/423#issuecomment-702553665) above, but this doesn't seem to have any effect. Here is the relevant line from my `home.nix` for reference: https://github.com/aergonaut/aether/blob/main/etc/nix/home.nix#L173 If I try `echo $TERMINFO_DIRS` in my shell, I can see the variable is set to some location in the Nix store. I don't know much about terminfo, however, so I don't know if it is set correctly.

The only thing that has worked for me has been prefixing `env TERM=xterm-256color` before `darwin-rebuild switch`, like @toonn [suggested](https://github.com/nix-community/home-manager/issues/423#issuecomment-515779123).

**Comment by ksexton** [comment] 2021-01-28 15:53
I was running into the same tput issue and was able to resolve it by adding

```
  environment.variables = {
    TERMINFO_DIRS = "${pkgs.kitty.terminfo.outPath}/share/terminfo";
  };
```

to my nix-darwin config.  If you are adding it to the zsh portion of your home-manager config, try moving it out of home-manager and into your darwin config to see if that helps.

**Comment by aergonaut** [comment] 2021-01-28 18:54
@ksexton That worked for me! Thanks!

**Comment by jacksonludwig** [comment] 2021-06-06 21:22
Would there be a way to resolve this without using home-manager to manage my env variables as suggested?

**Comment by SuperSandro2000** [comment] 2021-06-06 21:44
You don't manage all your ENVs with hm but only this one.

**Comment by jacksonludwig** [comment] 2021-06-06 21:49
My mistake, I didn't know I could do that. 

However, it seems that home-manager is still report the same issue about kitty terminfo.

**Comment by SuperSandro2000** [comment] 2021-06-07 00:25
```nix
home.sessionVariables = {
    TERMINFO_DIRS = "${pkgs.kitty.terminfo.outPath}/share/terminfo";
  };
```

**Comment by jacksonludwig** [comment] 2021-06-07 00:35
> 
> 
> ```nix
> home.sessionVariables = {
>     TERMINFO_DIRS = "${pkgs.kitty.terminfo.outPath}/share/terminfo";
>   };
> ```

Thanks for the help, but weirdly even with this config I get the same error.

**Comment by SuperSandro2000** [comment] 2021-06-07 00:46
You need to open a new shell otherwise hm does not reload the ENVs.

**Comment by jacksonludwig** [comment] 2021-06-07 00:52
> 
> 
> You need to open a new shell otherwise hm does not reload the ENVs.

Yep, I understand that. Even after restarting completely, though, it seems the ENV is not loaded as `echo $TERMINFO_DIRS` is blank.

**Comment by berbiche** [comment] 2021-06-07 14:08
> > 
> > 
> > You need to open a new shell otherwise hm does not reload the ENVs.
> 
> Yep, I understand that. Even after restarting completely, though, it seems the ENV is not loaded as `echo $TERMINFO_DIRS` is blank.

@jacksonludwig

I think you also need Home Manager to control your shell environment to properly source the environment variables.
One of `programs.<bash,zsh,fish>.enable = true`.

**Comment by lockejan** [comment] 2022-07-29 22:16
Hmm, is the suggested fix still valid? I can't reproduce a working state now. 🤔
During darwin-rebuild switch, it fails on the very end...
```
Activating home-manager configuration for lockejan
tput: unknown terminal "xterm-kitty"
```

I tried putting the fix in [darwin-conf.nix](https://github.com/lockejan/nix-dotfiles/blob/main/darwin/darwin-configuration.nix#L185) and home.nix, started a new terminal afterwards, without luck.

Only setting a different TERM on each invocation works for now.😬

**Comment by ciarand** [comment] 2022-08-02 23:01
I am also running into this with kitty and nix-darwin, even with the TERMINFO_DIRS variable set as described above:

```
$ darwin-rebuild switch --flake .
...
Activating home-manager configuration for ciaran.downey
tput: unknown terminal "xterm-kitty"
```

I don't know why it's failing though, because this seems to work fine:

```
$ tput -T xterm-kitty cols
80
```

My env from within kitty.app:

```
$ env | grep TERM
COLORTERM=truecolor
TERMINFO=/nix/store/l9r6mn1hjnhw3i5wfvbs1xl5finb3w7m-kitty-0.25.1/Applications/kitty.app/Contents/Resources/kitty/terminfo
TERM=xterm-kitty
TERMINFO_DIRS=/nix/store/vyvynacgm5vbhli833xysvkk0wmzix5j-kitty-0.25.1-terminfo/share/terminfo
```

My env from within the default terminal.app:

```
$ env | grep TERM
TERM_PROGRAM_VERSION=445
TERM_SESSION_ID=F7A77794-5996-4FE0-9B4B-3A5C594A496F
TERM=xterm-256color
TERMINFO_DIRS=/nix/store/vyvynacgm5vbhli833xysvkk0wmzix5j-kitty-0.25.1-terminfo/share/terminfo
TERM_PROGRAM=Apple_Terminal
```

For completeness, this works fine from within kitty.app too:

```
$ TERM=xterm-256color darwin-rebuild switch --flake .
...
$ echo $?
0
```

**Comment by toonn** [comment] 2022-08-03 09:40
I think activation scripts don't inherit the user's environment. So setting variables in a given user's environment may not affect them. Maybe activation scripts need to somehow collect all the appropriate terminfo dirs or explicitly inherit them from the invoking user?

**Comment by supermarin** [comment] 2022-08-12 16:44
Curious to see the solution for this one as well. With the flake based install (home-manager as a module), TERMINFO_DIRS hack doesn't work either in home-manager `home.sessionVariables` or nix-darwin `environment.variables`.

**Comment by supermarin** [comment] 2022-08-12 16:51
@SuperSandro2000 can we reopen this one?

**Comment by zwhitchcox** [comment] 2022-09-30 21:41
@ciarand Your solution worked for me, i.e.

```
TERM=xterm-256color nix --extra-experimental-features "nix-command flakes" build .#darwinConfigurations.system
```

Just wanted to let people know in case they were having trouble activating `nix-darwin` in kitty

**Comment by PhotonQuantum** [comment] 2022-10-12 23:54
I searched `tput` throughout the codebase and found three suspicious use:
https://github.com/nix-community/home-manager/blob/db00b39a9abec04245486a01b236b8d9734c9ad0/modules/lib-bash/color-echo.sh#L16
https://github.com/nix-community/home-manager/blob/9bcad2001386a086acda24ae973c230c7b06513f/lib/bash/home-manager.sh#L26
https://github.com/nix-community/home-manager/blob/9bcad2001386a086acda24ae973c230c7b06513f/lib/bash/color-echo#L18

IMO these calls are to detect color support of the terminal. So why not fall back to `nocolor` when `tput` fails?

**Comment by rycee** [comment] 2022-10-13 10:36
Made a quick implementation of @PhotonQuantum's suggestion. Hopefully it makes things work!

**Closed** 2022-10-13 10:35 UTC

**Comment by supermarin** [comment] 2022-10-13 18:39
Just to put it on the table, ssh-ing into other machines is still not fixed with this approach.
I guess this goes beyond home-manager (nix / terminfo), but fixes like this just help putting it under the rug.

**Comment by rycee** [comment] 2022-10-13 19:36
@supermarin That doesn't seem related to Home Manager, just a general lack of terminfo? So I think that would be a bug for Nixpkgs.

**Comment by supermarin** [comment] 2022-10-14 16:09
Gotcha, agreed
