### ISSUE TITLE
bug: program.zsh.completion breaks nix completion.

### ISSUE THREAD

**Issue by QuantMint** [nix-community/home-manager#3361] opened 2022-10-29 12:27 UTC
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Since a few days ago if enableCompletion is enabled the nix command completions are broken.
For example when I write nix run nixpkgs#firef and press tab the result is:
❯ nix run nixpkgs#firef
nix
When enableCompletion is disabled everything work as usual.
This could be related to: https://github.com/NixOS/nixpkgs/pull/197503

### Maintainer CC

@CardboardTurkey 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.0.0-xanmod1, NixOS, 22.11 (Raccoon), 22.11.20221028.448a599`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - channels(quantmint): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Kranzes** [comment] 2022-11-04 12:52
I am experiencing the same issue for the past couple of weeks, it's only for the Nix package/program.

**Comment by Gerschtli** [comment] 2022-11-06 15:41
If `enableCompletion = false;`  solves the issue, it seems `compinit` may be called before nix completions are set to `fpath`.

**Comment by wentasah** [comment] 2022-11-22 22:19
This seems to be a [bug in nix-zsh-completions](https://github.com/spwhitt/nix-zsh-completions/issues/42). When `enableCompletion = true`, this package is installed and its `_nix` completion function is used instead of the [zsh completion function provided directly by nix](https://github.com/NixOS/nix/blob/05d0892443bbe92a6b6a1ee7b1d37ea05782d918/misc/zsh/completion.zsh).

I work around this problem by removing `_nix` from `nix-zsh-completions`. I do it via the following nixpkgs overlay:
```nix
(final: prev: {
  nix-zsh-completions = prev.nix-zsh-completions.overrideAttrs (old: {  postPatch = "rm _nix"; });
})
```

**Comment by QuantMint** [comment] 2022-11-23 11:02
EnableCompletion enables [nix-zsh-completions](https://github.com/spwhitt/nix-zsh-completions) that is basically unmaintained and not required considering that nix itself provides zsh completions, would make sense to just remove the to fix this issue?

**Comment by wentasah** [comment] 2022-11-23 23:38
But `nix-zsh-completions` contains completions for other commands such as nix-build, nix-env, nixos-rebuild, which seem to work. Removing the whole package would remove these completions that people might use.

It seems that the problem is more subtle. [`nix-zsh-completions` sets its priority to 6](https://github.com/NixOS/nixpkgs/blob/c9538a9b7074925ac117835c775fb81d0e7f98fa/pkgs/shells/zsh/nix-zsh-completions/default.nix#L24), which means that installing it together with `nix`, should result in `nix`'s completion to override the one from `nix-zsh-completions`. This is usually the case when `nix-zsh-completions` is installed in system profile. Home-manager usually doesn't install `nix` to the home profile so `_nix` is not overridden.

I think, we can tell home-manager to install overridden `nix-zsh-completions` as in my above comment. I'll send a PR soon.

**Comment by Kranzes** [comment] 2022-11-24 00:47
When did it break and why? Why did we never have the need to do this sort of stuff until a month ago or so?

**Comment by wentasah** [comment] 2022-11-24 23:17
I confirm that https://github.com/NixOS/nixpkgs/pull/197503 is the reason for the buggy behavior. Before that PR, `$fpath` contained `/run/current-system/sw/share/zsh/site-functions` before `/etc/profiles/per-user/wsh/share/zsh/site-functions`, which is in my case managed by home-manager. After the PR, the order is the opposite.

`/run/current-system/sw/share/zsh/site-functions` contains the `_nix` file from the nix package, while the `/etc/profiles/per-user/wsh/share/zsh/site-functions` contains buggy `_nix` from [nix-zsh-completions](https://github.com/spwhitt/nix-zsh-completions). The latter seems to be buggy because it parses the output of `nix --help`, which now contains some confusing ANSI escape sequences.

An alternative solution would be to patch `nix-zsh-completions` directly in nixpkgs. When thinking about that, it might be better place for this kind of change.

**Comment by wentasah** [comment] 2022-11-24 23:53
FYI: https://github.com/NixOS/nixpkgs/pull/202750

**Comment by wentasah** [comment] 2022-11-30 22:47
Fix is merged in nixpkgs (both [unstable](https://nixpk.gs/pr-tracker.html?pr=202750) and [22.11](https://nixpk.gs/pr-tracker.html?pr=203669)). It will probably take few hours (or days) to reach all channels, and then this could be closed, IMO.

**Closed** 2022-12-01 15:17 UTC
Labels: bug, triage, shell
