### ISSUE TITLE
Home.nix doesn't seem to be respecting neovim extraConfig anymore

### ISSUE THREAD

**Issue by RonanMacF** [nix-community/home-manager#2040] opened 2021-05-27 18:33 UTC
In my neovim config I point towards my config file, e.g. `extraConfig = builtins.readFile ~/dotfiles/nvim/config.vim;`. This has always worked fine but today after running `nix-channel --update && home-manager switch` it has now stopped reading this file. When I go back to the previous generation it reads it. I can get it to read it by manually sourcing the file when I'm in neovim but I shouldn't have to do this. I also tried doing
```
extraConfig = ''
source ~/dotfiles/nvim/config.vim;
'';
```
but this also didn't result in the config being read on start. Something changed over the past couple of days.

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.4.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(ronan): `"home-manager, nixpkgs-21.11pre292293.84aa23742f6"`
 - nixpkgs: `/Users/ronan/.nix-defexpr/channels/nixpkgs`
 ```

**Comment by davidarmstronglewis** [comment] 2021-05-27 19:01
Glad you reported this, I ran into the same issue this morning while running my usual system update. I'm also using `extraConfig` with some inline configuration. `~/.config/nvim/init.vim` is still being created, but my `extraConfig` isn't being concatenated to it.

**Comment by sumnerevans** [comment] 2021-05-27 19:22
@teto, any ideas since you have been working on things related to neovim lately in https://github.com/nix-community/home-manager/pull/1945

**Comment by teto** [comment] 2021-05-27 19:44
You should be able to cherry-pick either 
https://github.com/nix-community/home-manager/pull/2039 or (I had prepared https://github.com/nix-community/home-manager/pull/1945 from some time). Going to merge the latter soon.

**Comment by teto** [comment] 2021-05-27 20:04
problem is I can't merge because it breaks the CI. Looking forward to https://github.com/nix-community/home-manager/pull/1934 being merged so that dependencies are clearer.

**Comment by teto** [comment] 2021-05-27 20:13
I've merged the partial fix from @expipiplus1 . It should solve this specific issue (but your neovim will load its config via `nvim -u /nix/store/...` instead of the ~/.config/nvim/init.vim. It shouldn't matter if you dont use project specific .vimrc files.

**Comment by davidarmstronglewis** [comment] 2021-05-27 22:46
I was able to run `nix-channel --update && darwin-rebuild switch` and confirm that the configuration now applies properly. Thank you, @teto!

**Comment by foolnotion** [comment] 2021-05-28 10:07
this fixes nvim but it looks like neovim-qt config is also broken unless launched with `nvim-qt -- -u .config/nvim/init.vim`

**Comment by teto** [comment] 2021-05-28 15:36
home-manager + a master nixpkgs stops generating init.vim until https://github.com/nix-community/home-manager/pull/1945/files#diff-c92c817e3e106b0ade6a328e38b3f1d965fe03a75a3090202cb5e72cc1fac2aeR254 is merged, If you just add this line, home-manager should start generating ~/.config/nvim/init.vim again and it should fix it your issue.

**Comment by foolnotion** [comment] 2021-05-28 18:26
in my case, after a `nix-channel --update`, `~/.config/nvim/init.vim` is correctly generated again, `nvim` and all its plugins work fine -- no problem here.

But as of this issue #2040 (or other related issues mentioned here), `nvim-qt` does not load the nvim config anymore (prior to loading its own `~/config/nvim/ginit.vim`). I am only describing the symptoms as I don't have a real explanation, but it seems like nvim GUIs might still be broken to some extent.

**Comment by teto** [comment] 2021-05-28 18:35
nvim-qt does nothing special, it just adds the wrapped neovim in its PATH. Either the neovim explicitly sets its config or it loads from ~/.config/nvim/init.vim

**Comment by rycee** [comment] 2021-05-30 08:17
Is this related to the test failures that the master branch is seeing?

```
 neovim-plugin-config: FAILED
Expected /dev/fd/63 to be same as /nix/store/mnmshji5clb5xi1wvvz6cw7kc6ww0gbf-plugin-config.vim but were different:
--- actual
+++ expected
@@ -0,0 +1,13 @@
+" configuration generated by NIX
+set nocompatible
+
+set packpath^=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vim-pack-dir
+set runtimepath^=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vim-pack-dir
+
+" This should be present in vimrc
+" vim-commentary {{{
+" This should be present too
+autocmd FileType c setlocal commentstring=//\ %s
+autocmd FileType c setlocal comments=://
+
+" }}}
For further reference please introspect /nix/store/pi673n2ssh5vmclacc9ycxqlygdrnb8j-nmt-report-neovim-plugin-config
```

**Comment by teto** [comment] 2021-05-30 16:34
possibly, could we switch the tests to use the flake instead ? it would increase reproducibility and lockstep improvements. Right now with the changes done to neovim, either it breaks for people following master or it breaks for unstable trackers. With the flake we could reference a rev that always works (i.e., whose tests all pass).

**Comment by berbiche** [comment] 2021-05-30 20:37
> possibly, could we switch the tests to use the flake instead ? it would increase reproducibility and lockstep improvements. Right now with the changes done to neovim, either it breaks for people following master or it breaks for unstable trackers. With the flake we could reference a rev that always works (i.e., whose tests all pass).

There was some work here https://github.com/nix-community/home-manager/pull/1146. It would need to be revived.

**Comment by rycee** [comment] 2021-05-30 21:35
I would prefer to keep the tests tracking the nixpkgs-unstable channel since that is the primary distribution method of Nixpkgs master. The hope is that using `nixpkgs=channel:nixos-unstable` will lead to prompt discovery of when Nixpkgs introduce changes that break HM.

**Comment by teto** [comment] 2021-05-30 22:25
the flake could track nixos-unstable but stops updating when there is a build failure (that's where the .lock file comes in) so that users can use a home-manager that always passes the tests. When tests break, it will delay the update of the flake.lock until we fix the tests. Right now it's annoying because even if I have a fix against master, I can't push it because it will break for those tracking unstable. Plus flake.lock is easier to read than parsing the output of the travis job, (./format uses a different nixpkgs than the tests :s )

**Comment by berbiche** [comment] 2021-06-07 22:01
Closing this since #2039 is merged.

**Closed by berbiche** 2021-06-07 22:01 UTC

**Comment by peperunas** [comment] 2021-06-25 14:35
I believe I am still encountering this issue.

This is my current setup:

```
 programs.neovim = {
    enable = true; 
    extraConfig = ''
      syntax enable 
      set termguicolors 
      colorscheme monokai_pro 
    '';
    viAlias = true; 
    vimAlias = true;
    plugins = with pkgs.vimPlugins; [ 
      vim-nix 
      vim-monokai-pro 
      YouCompleteMe 
      vim-airline 
      vim-lsp 
      fugitive ];
    };
}
```

This is the `init.vim`:

```
set packpath^=/nix/store/9bi68z8yi1r5ci5vs8y1wg1djr6zj7h5-vim-pack-dir
set runtimepath^=/nix/store/9bi68z8yi1r5ci5vs8y1wg1djr6zj7h5-vim-pack-dir
```

I have run `nix-channel --update` and `home-manager switch`.

**Comment by teto** [comment] 2021-06-25 17:32
this is just too vague to help you. nix-channel --update doesnt tell us which channels, what revision ? tests pass for current nixos-unstable so make sure you've updated correctly.

**Comment by peperunas** [comment] 2021-06-25 18:21
I am sorry @teto, I am new to home-manager and nix in general.

What should I run to give more information?

```
$ nix-channel --list
home-manager https://github.com/nix-community/home-manager/archive/master.tar.gz
nixos https://nixos.org/channels/nixos-21.05
```

**Comment by peperunas** [comment] 2021-06-27 16:58
I believe the channel is up-to-date on my setup.

```
$ sha256sum ~/.nix-defexpr/channels/home-manager/modules/programs/neovim.nix
4004322f572d89b6f072d3b79dd5c2830c428f506107a75f33acd5f386c6a4cf

$ curl https://raw.githubusercontent.com/nix-community/home-manager/master/modules/programs/neovim.nix | sha256sum
4004322f572d89b6f072d3b79dd5c2830c428f506107a75f33acd5f386c6a4cf
```

**Comment by teto** [comment] 2021-06-27 20:38
have you run a nix-rebuild ? unstable + master is the combination tested on CI and tests pass (no issue on my machine either) so I am not sure what is wrong.

**Comment by rycee** [comment] 2021-06-28 06:41
@peperunas Might be that there actually is some older Nixpkgs around, that gets picked up through NIX_PATH. Try running `nix-shell -p nix-info --run "nix-info -m"`.

**Comment by peperunas** [comment] 2021-06-28 11:26
@teto, yes I have run `nixos-rebuild switch`.

@rycee, this is the output:

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.45, NixOS, 21.05.1205.b72bde7c4a1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"home-manager, nixos-21.05.1205.b72bde7c4a1"`
 - channels(giulio): `"home-manager, nixos-21.11pre297796.e1f8852faac"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by teto** [comment] 2021-06-28 11:31
do you use home-manager as a module or as a standalone in which case you have to run home-manager switch ? `sudo nix-channel ` != `nix-channel` hence the different revisions

**Comment by peperunas** [comment] 2021-06-28 11:36
@teto, I use `home-manager` as a standalone and I always ran `home-manager switch`.
The channel URI for `nixos` is the same, though. Should I have a different commit but same base version when running `[sudo] nix-channel`?

**Comment by sumnerevans** [comment] 2021-06-28 15:06
@peperunas you can join [#hm:rycee.net](https://matrix.to/#/#hm:rycee.net) if you want. That room is also bridged to OFTC.
