### ISSUE TITLE
vim plugin module errors on latest unstable

### ISSUE THREAD

**Issue by legendofmiracles** [nix-community/home-manager#2326] opened 2021-09-13 16:16 UTC
After I updated my flake and rebuilt today I got hit with this:

```
error: attribute 'pname' missing

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/pkgs/misc/vim-plugins/vim-utils.nix:200:50:

          199|     linkVimlPlugin = plugin: packageName: dir: ''
          200|       mkdir -p $out/pack/${packageName}/${dir}/${plugin.pname}
             |                                                  ^
          201|       ln -sf ${plugin}/${rtpPath}/* $out/pack/${packageName}/${dir}/${plugin.pname}
(use '--show-trace' to show detailed location information)
```
This seems to be home-managers own nixpkgs clone, since my nixpkgs store path is a different one.

**Comment by berbiche** [comment] 2021-09-13 17:59
Can you show the output with `--show-trace`?

This might hint as to which package is missing the `pname` attribute.

**Comment by legendofmiracles** [comment] 2021-09-13 18:19
```
$ nixos-rebuild switch --flake dotnix/ --show-trace
warning: Git tree '/home/nix/dotnix' is dirty
building the system configuration...
warning: Git tree '/home/nix/dotnix' is dirty
error: attribute 'pname' missing

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/pkgs/misc/vim-plugins/vim-utils.nix:200:50:

          199|     linkVimlPlugin = plugin: packageName: dir: ''
          200|       mkdir -p $out/pack/${packageName}/${dir}/${plugin.pname}
             |                                                  ^
          201|       ln -sf ${plugin}/${rtpPath}/* $out/pack/${packageName}/${dir}/${plugin.pname}

       … while evaluating 'linkVimlPlugin'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/pkgs/misc/vim-plugins/vim-utils.nix:199:43:

          198|
          199|     linkVimlPlugin = plugin: packageName: dir: ''
             |                                           ^
          200|       mkdir -p $out/pack/${packageName}/${dir}/${plugin.pname}

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/pkgs/misc/vim-plugins/vim-utils.nix:224:28:

          223|       # to `start` (except if they are explicitly listed as optional plugins).
          224|       ++ (builtins.map (x: link x packageName "start") allPlugins)
             |                            ^
          225|       ++ ["mkdir -p $out/pack/${packageName}/opt"]

       … while evaluating anonymous lambda

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/pkgs/misc/vim-plugins/vim-utils.nix:224:25:

          223|       # to `start` (except if they are explicitly listed as optional plugins).
          224|       ++ (builtins.map (x: link x packageName "start") allPlugins)
             |                         ^
          225|       ++ ["mkdir -p $out/pack/${packageName}/opt"]

       … from call site

       … while evaluating 'flatten'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:137:13:

          136|   */
          137|   flatten = x:
             |             ^
          138|     if isList x

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:139:24:

          138|     if isList x
          139|     then concatMap (y: flatten y) x
             |                        ^
          140|     else [x];

       … while evaluating anonymous lambda

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:139:21:

          138|     if isList x
          139|     then concatMap (y: flatten y) x
             |                     ^
          140|     else [x];

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:139:10:

          138|     if isList x
          139|     then concatMap (y: flatten y) x
             |          ^
          140|     else [x];

       … while evaluating 'flatten'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:137:13:

          136|   */
          137|   flatten = x:
             |             ^
          138|     if isList x

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:139:24:

          138|     if isList x
          139|     then concatMap (y: flatten y) x
             |                        ^
          140|     else [x];

       … while evaluating anonymous lambda

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:139:21:

          138|     if isList x
          139|     then concatMap (y: flatten y) x
             |                     ^
          140|     else [x];

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:139:10:

          138|     if isList x
          139|     then concatMap (y: flatten y) x
             |          ^
          140|     else [x];

       … while evaluating 'flatten'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:137:13:

          136|   */
          137|   flatten = x:
             |             ^
          138|     if isList x

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/pkgs/misc/vim-plugins/vim-utils.nix:239:51:

          238|         src = ./.;
          239|         installPhase = lib.concatStringsSep "\n" (lib.flatten (lib.mapAttrsToList packageLinks packages));
             |                                                   ^
          240|         preferLocalBuild = true;

       … while evaluating the attribute 'installPhase' of the derivation 'vim-pack-dir'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/pkgs/stdenv/generic/make-derivation.nix:207:7:

          206|         let
          207|           # Indicate the host platform of the derivation if cross compiling.
             |       ^
          208|           # Fixed-output derivations like source tarballs shouldn't get a host

       … while evaluating 'nativeImpl'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/pkgs/misc/vim-plugins/vim-utils.nix:190:16:

          189|
          190|   nativeImpl = packages:
             |                ^
          191|   (let

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/pkgs/misc/vim-plugins/vim-utils.nix:385:61:

          384|       ]
          385|       ++ lib.optional (packages != null && packages != []) (nativeImpl packages)
             |                                                             ^
          386|       ++ lib.optional (pathogen != null) pathogenImpl

       … while evaluating anonymous lambda

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/pkgs/misc/vim-plugins/vim-utils.nix:391:46:

          390|     in
          391|       lib.concatStringsSep "\n" (lib.filter (x: x != null && x != "") entries);
             |                                              ^
          392|

       … from call site

       … while evaluating 'vimrcContent'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/pkgs/misc/vim-plugins/vim-utils.nix:261:18:

          260|    */
          261|   vimrcContent = {
             |                  ^
          262|     packages ? null,

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/pkgs/applications/editors/neovim/utils.nix:123:25:

          122|       manifestRc = vimUtils.vimrcContent (configurePatched // { customRC = ""; }) ;
          123|       neovimRcContent = vimUtils.vimrcContent configurePatched;
             |                         ^
          124|     in

       … while evaluating the attribute 'neovimRcContent'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/pkgs/applications/editors/neovim/utils.nix:129:14:

          128|       wrapperArgs = makeWrapperArgs;
          129|       inherit neovimRcContent;
             |              ^
          130|       inherit manifestRc;

       … while evaluating the attribute 'condition'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:693:14:

          692|     { _type = "if";
          693|       inherit condition content;
             |              ^
          694|     };

       … while evaluating 'dischargeProperties'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:609:25:

          608|   */
          609|   dischargeProperties = def:
             |                         ^
          610|     if def._type or "" == "merge" then

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:538:137:

          537|         defs' = concatMap (m:
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          539|         ) defs;

       … while evaluating definitions from `/nix/store/wwpy1zrj5b8rsbja4481y2fz9h8sbx3z-source/modules/programs/neovim.nix':

       … while evaluating anonymous lambda

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:537:28:

          536|         # Process mkMerge and mkIf properties.
          537|         defs' = concatMap (m:
             |                            ^
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:537:17:

          536|         # Process mkMerge and mkIf properties.
          537|         defs' = concatMap (m:
             |                 ^
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:650:7:

          649|     in {
          650|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          651|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:551:9:

          550|       in {
          551|         values = defs''';
             |         ^
          552|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'optionalValue'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:569:5:

          568|
          569|     optionalValue =
             |     ^
          570|       if isDefined then { value = mergedValue; }

       … while evaluating anonymous lambda

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/types.nix:394:86:

          393|       merge = loc: defs:
          394|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:
             |                                                                                      ^
          395|             (mergeDefinitions (loc ++ [name]) elemType defs).optionalValue

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:369:15:

          368|       inherit name;
          369|       value = f name (catAttrs name sets);
             |               ^
          370|     }) names);

       … while evaluating the attribute '"nvim/init.vim"'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:369:7:

          368|       inherit name;
          369|       value = f name (catAttrs name sets);
             |       ^
          370|     }) names);

       … while evaluating anonymous lambda

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/types.nix:394:51:

          393|       merge = loc: defs:
          394|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:
             |                                                   ^
          395|             (mergeDefinitions (loc ++ [name]) elemType defs).optionalValue

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:128:62:

          127|   filterAttrs = pred: set:
          128|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |                                                              ^
          129|

       … while evaluating anonymous lambda

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:128:29:

          127|   filterAttrs = pred: set:
          128|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |                             ^
          129|

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:128:18:

          127|   filterAttrs = pred: set:
          128|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |                  ^
          129|

       … while evaluating 'filterAttrs'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:127:23:

          126|   */
          127|   filterAttrs = pred: set:
             |                       ^
          128|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/types.nix:394:35:

          393|       merge = loc: defs:
          394|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:
             |                                   ^
          395|             (mergeDefinitions (loc ++ [name]) elemType defs).optionalValue

       … while evaluating 'merge'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/types.nix:393:20:

          392|       check = isAttrs;
          393|       merge = loc: defs:
             |                    ^
          394|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:559:59:

          558|       if isDefined then
          559|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                                                           ^
          560|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … while evaluating the attribute 'mergedValue'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:557:5:

          556|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          557|     mergedValue =
             |     ^
          558|       if isDefined then

       … while evaluating the option `home-manager.users.nix.xdg.configFile':

       … while evaluating the attribute 'value'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:525:9:

          524|     in warnDeprecation opt //
          525|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          526|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:140:72:

          139|           # For definitions that have an associated option
          140|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          141|

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:304:20:

          303|               then recurse (path ++ [name]) value
          304|               else f (path ++ [name]) value;
             |                    ^
          305|         in mapAttrs g set;

       … while evaluating 'g'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:301:19:

          300|           g =
          301|             name: value:
             |                   ^
          302|             if isAttrs value && cond value

       … from call site

       … while evaluating 'mapAttrs''

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:242:18:

          241|   */
          242|   mapAttrs' = f: set:
             |                  ^
          243|     listToAttrs (map (attr: f attr set.${attr}) (attrNames set));

       … from call site

       at /nix/store/wwpy1zrj5b8rsbja4481y2fz9h8sbx3z-source/modules/misc/xdg.nix:98:10:

           97|       home.file = mkMerge [
           98|         (mapAttrs'
             |          ^
           99|           (name: file: nameValuePair "${config.xdg.configHome}/${name}" file)

       … while evaluating 'dischargeProperties'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:609:25:

          608|   */
          609|   dischargeProperties = def:
             |                         ^
          610|     if def._type or "" == "merge" then

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:611:7:

          610|     if def._type or "" == "merge" then
          611|       concatMap dischargeProperties def.contents
             |       ^
          612|     else if def._type or "" == "if" then

       … while evaluating 'dischargeProperties'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:609:25:

          608|   */
          609|   dischargeProperties = def:
             |                         ^
          610|     if def._type or "" == "merge" then

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:538:137:

          537|         defs' = concatMap (m:
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          539|         ) defs;

       … while evaluating definitions from `/nix/store/wwpy1zrj5b8rsbja4481y2fz9h8sbx3z-source/modules/misc/xdg.nix':

       … while evaluating anonymous lambda

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:537:28:

          536|         # Process mkMerge and mkIf properties.
          537|         defs' = concatMap (m:
             |                            ^
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:537:17:

          536|         # Process mkMerge and mkIf properties.
          537|         defs' = concatMap (m:
             |                 ^
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:650:7:

          649|     in {
          650|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          651|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:551:9:

          550|       in {
          551|         values = defs''';
             |         ^
          552|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'mergedValue'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:557:5:

          556|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          557|     mergedValue =
             |     ^
          558|       if isDefined then

       … while evaluating the option `home-manager.users.nix.home.file':

       … while evaluating the attribute 'value'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:525:9:

          524|     in warnDeprecation opt //
          525|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          526|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/modules.nix:140:72:

          139|           # For definitions that have an associated option
          140|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          141|

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:304:20:

          303|               then recurse (path ++ [name]) value
          304|               else f (path ++ [name]) value;
             |                    ^
          305|         in mapAttrs g set;

       … while evaluating 'g'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:301:19:

          300|           g =
          301|             name: value:
             |                   ^
          302|             if isAttrs value && cond value

       … from call site

       … while evaluating 'mapAttrsToList'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:258:23:

          257|   */
          258|   mapAttrsToList = f: attrs:
             |                       ^
          259|     map (name: f name attrs.${name}) (attrNames attrs);

       … from call site

       at /nix/store/wwpy1zrj5b8rsbja4481y2fz9h8sbx3z-source/modules/files.nix:48:14:

           47|             (foldAttrs (acc: v: acc + v) 0
           48|             (mapAttrsToList (n: v: { ${v.target} = 1; }) cfg)));
             |              ^
           49|         dupsStr = concatStringsSep ", " dups;

       … while evaluating 'fold''

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:55:15:

           54|       len = length list;
           55|       fold' = n:
             |               ^
           56|         if n == len

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:59:8:

           58|         else op (elemAt list n) (fold' (n + 1));
           59|     in fold' 0;
             |        ^
           60|

       … while evaluating 'foldr'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:52:20:

           51|   */
           52|   foldr = op: nul: list:
             |                    ^
           53|     let

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:158:5:

          157|   foldAttrs = op: nul: list_of_attrs:
          158|     foldr (n: a:
             |     ^
          159|         foldr (name: o:

       … while evaluating 'foldAttrs'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:157:24:

          156|   */
          157|   foldAttrs = op: nul: list_of_attrs:
             |                        ^
          158|     foldr (n: a:

       … from call site

       at /nix/store/wwpy1zrj5b8rsbja4481y2fz9h8sbx3z-source/modules/files.nix:47:14:

           46|             (filterAttrs (n: v: v > 1)
           47|             (foldAttrs (acc: v: acc + v) 0
             |              ^
           48|             (mapAttrsToList (n: v: { ${v.target} = 1; }) cfg)));

       … while evaluating 'filterAttrs'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/attrsets.nix:127:23:

          126|   */
          127|   filterAttrs = pred: set:
             |                       ^
          128|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));

       … from call site

       at /nix/store/wwpy1zrj5b8rsbja4481y2fz9h8sbx3z-source/modules/files.nix:46:14:

           45|           attrNames
           46|             (filterAttrs (n: v: v > 1)
             |              ^
           47|             (foldAttrs (acc: v: acc + v) 0

       … while evaluating the attribute 'assertion'

       at /nix/store/wwpy1zrj5b8rsbja4481y2fz9h8sbx3z-source/modules/files.nix:51:9:

           50|       in {
           51|         assertion = dups == [];
             |         ^
           52|         message = ''

       … while evaluating the attribute 'assertion'

       at /nix/store/wwpy1zrj5b8rsbja4481y2fz9h8sbx3z-source/nixos/default.nix:115:28:

          114|       flip map config.assertions (assertion: {
          115|         inherit (assertion) assertion;
             |                            ^
          116|         message = "${user} profile: ${assertion.message}";

       … while evaluating anonymous lambda

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/nixos/modules/system/activation/top-level.nix:126:50:

          125|
          126|   failedAssertions = map (x: x.message) (filter (x: !x.assertion) config.assertions);
             |                                                  ^
          127|

       … from call site

       … while evaluating 'fold''

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:55:15:

           54|       len = length list;
           55|       fold' = n:
             |               ^
           56|         if n == len

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:59:8:

           58|         else op (elemAt list n) (fold' (n + 1));
           59|     in fold' 0;
             |        ^
           60|

       … while evaluating 'foldr'

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/lib/lists.nix:52:20:

           51|   */
           52|   foldr = op: nul: list:
             |                    ^
           53|     let

       … from call site

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/nixos/modules/system/activation/top-level.nix:133:12:

          132|   # Replace runtime dependencies
          133|   system = foldr ({ oldDependency, newDependency }: drv:
             |            ^
          134|       pkgs.replaceDependency { inherit oldDependency newDependency drv; }
```

**Comment by berbiche** [comment] 2021-09-13 19:47
@legendofmiracles do you have custom vim plugins?

I evaluated the following in an repl and could not reproduce the issue which is why I believe the error might come from a use of custom vim plugins.

``` console
$ nix repl channel:nixos-unstable-small
nix-repl> lib.filterAttrs (_: v: !(builtins.tryEval (v ? pname || lib.isFunction v)).value) vimPlugins
{ gist-vim = «error: error: gist-vim was renamed to vim-gist on 2020-03-27. Please update to vim-gist.»;
  nvim-bufferline-lua = «error: error: nvim-bufferline-lua was renamed to bufferline-nvim on 2021-08-22. Please update to bufferline-nvim.»;
  nvim-lsp = «error: error: nvim-lsp was renamed to nvim-lspconfig on 2020-08-31. Please update to nvim-lspconfig.»;
  nvim-toggleterm-lua = «error: error: nvim-toggleterm-lua was renamed to toggleterm-nvim on 2021-08-22. Please update to toggleterm-nvim.»;
  recurseForDerivations = true;
  sql-nvim = «error: error: sql-nvim was renamed to sqlite-lua on 2021-09-03. Please update to sqlite-lua.»;
  vim-jade = «error: error: vim-jade was renamed to vim-pug on 2020-03-27. Please update to vim-pug.»;
  vundle = «error: error: vundle was renamed to Vundle-vim on 2020-03-27. Please update to Vundle-vim.»;
  youcompleteme = «error: error: youcompleteme was renamed to YouCompleteMe on 2020-03-27. Please update to YouCompleteMe.»; }
```

**Comment by legendofmiracles** [comment] 2021-09-13 21:20
> custom vim plugins

Yes, I build some plugins that are not packaged in nix on my own. 
https://github.com/legendofmiracles/dotnix/blob/0872670de082dac3e18c0d17bcf262c30c838e02/hm/nvim.nix in the first few lines. 

However I do not think that it's my fault, since someone else - with their own configuration, could also reproduce this.

**Comment by mbprtpmnr** [comment] 2021-09-14 02:28
Same error after `nix flake update` ...

```
[mbprtpmnr@nixos:~/tmp/dotnix]$ home-manager switch --flake .#mbprtpmnr@nixos --verbose
error: attribute 'pname' missing

       at /nix/store/mz7v4wj3avpp6a1r2iygm17hbcaq9yrv-source/pkgs/misc/vim-plugins/vim-utils.nix:200:50:

          199|     linkVimlPlugin = plugin: packageName: dir: ''
          200|       mkdir -p $out/pack/${packageName}/${dir}/${plugin.pname}
             |                                                  ^
          201|       ln -sf ${plugin}/${rtpPath}/* $out/pack/${packageName}/${dir}/${plugin.pname}
(use '--show-trace' to show detailed location information)
```

**Comment by berbiche** [comment] 2021-09-14 05:28
Hi,

This isn't an issue with Home Manager but with the plugins you are using.

The breakage was introduced in https://github.com/NixOS/nixpkgs/commit/56f823dd5c596ef6374f99a22ca63168ff6f6fb9.

Make sure the derivations you are creating with `buildVimPlugin` or anything else have the `pname` attribute set.
In @legendofmiracles case, I believe the fix is to simply change `name` to `pname` in all your calls to `buildVimPlugin`.

I will be closing this issue.

**Closed** 2021-09-14 05:29 UTC

**Comment by legendofmiracles** [comment] 2021-09-14 15:22
Thanks for the solution! I'm sorry for opening an issue when it was my fault all along

**Comment by berbiche** [comment] 2021-09-17 04:59
> Thanks for the solution! I'm sorry for opening an issue when it was my fault all along

No problem! I encountered this issue earlier yesterday when upgrading my nixpkgs revision.
