### ISSUE TITLE
opening lock file '/nix/var/nix/profiles/per-user/root/home-manager.lock': No such file or directory

### ISSUE THREAD

**Issue by emils0** [nix-community/home-manager#3734] opened 2023-03-02 19:19 UTC
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When installing home-manager on a non-NixOS Linux Distro, I am encountering an error during installation.

```
$ nix-shell '<home-manager>' -A install

Creating initial Home Manager generation...

/nix/store/sgbp7cxbaclil0jchnrswqhjdsp5bfv7-home-manager-generation
Starting Home Manager activation
error: opening lock file '/nix/var/nix/profiles/per-user/root/home-manager.lock': No such file or directory
Uh oh, the installation failed! Please create an issue at

    https://github.com/nix-community/home-manager/issues

if the error seems to be the fault of Home Manager.
```

This fails consistently, and I have attempted to install it on multiple distros inside of WSL, including Ubuntu, Debian, and Arch.

A friend of mine is also experiencing this exact issue, but he's running Fedora on bare-metal, so this does not seem to be exclusively happening on WSL.

I have also tried installing home-manager on both multi-user Nix installs, and single-user, but the result is the same.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.16.3-microsoft-standard-WSL2, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`
```

**Comment by ncfavier** [comment] 2023-03-02 19:40
This is a consequence of https://github.com/nix-community/home-manager/issues/2544, which is starting to cause issues with Nix 2.14 because the default profile location changed, see https://github.com/NixOS/nix/issues/7930.

**Comment by propet** [comment] 2023-03-03 11:26
I'm on a Kali linux host, and I could solve this issue by doing:
```
mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
```

**Comment by rycee** [comment] 2023-03-03 16:42
I'll try to get this resolved over the weekend.

**Comment by thiagokokada** [comment] 2023-03-04 10:57
A similar issue also happens before `2.14` when you try use the store located in `~/.local/share/nix/root`, that is used automatically since 2.10 (see: https://discourse.nixos.org/t/nix-2-10-0-released/20291) if you don't have permissions to write in `/nix` (e.g. Steam Deck).

So having this bug fixed can be interesting since it would mean that we could have Home-Manager running in almost any Linux system that supports user-namespaces and access to Nix static binaries.

**Comment by rycee** [comment] 2023-03-05 07:52
@thiagokokada Hmm, wouldn't setting [NIX_STATE_DIR](https://nixos.org/manual/nix/stable/command-ref/env-common.html#env-NIX_STATE_DIR) work in that case?

**Comment by thiagokokada** [comment] 2023-03-05 11:24
> @thiagokokada Hmm, wouldn't setting [NIX_STATE_DIR](https://nixos.org/manual/nix/stable/command-ref/env-common.html#env-NIX_STATE_DIR) work in that case?

No, for two reasons:
- If you set `NIX_STATE_DIR` globally (like `export NIX_STATE_DIR=~/.local/share/nix/var/nix`, it makes `nix` assume that the store is once again localized in `/nix/store` (I think this is a bug in `nix`, not sure yet). Once it tries to write it fails.
- If you set only for the activation script, it goes further but stops later for some other reason that I didn't had enough time to debug yet.

**Comment by cvoges12** [comment] 2023-03-05 14:36
Yeah, I also have this issue. Reproducible on Debian.

**Comment by thiagokokada** [comment] 2023-03-05 21:23
With the following patch:

```
diff --git a/modules/lib-bash/activation-init.sh b/modules/lib-bash/activation-init.sh
index 3b0f5320..24735cc5 100644
--- a/modules/lib-bash/activation-init.sh
+++ b/modules/lib-bash/activation-init.sh
@@ -1,7 +1,16 @@
+function nixStateDir() {
+    local nixStateDir="/nix/var/nix"
+    if [[ ! -d "$nixStateDir" ]]; then
+        nixStateDir="${XDG_DATA_HOME:-$HOME/.local/share}/nix"
+    fi
+    # NIX_STATE_DIR has priority over directory auto-detection
+    echo "${NIX_STATE_DIR:-$nixStateDir}"
+}
+
 function setupVars() {
-    local nixStateDir="${NIX_STATE_DIR:-/nix/var/nix}"
-    local profilesPath="$nixStateDir/profiles/per-user/$USER"
-    local gcPath="$nixStateDir/gcroots/per-user/$USER"
+    local -r nixStateDir="$(nixStateDir)"
+    local -r profilesPath="$nixStateDir/profiles/per-user/$USER"
+    local -r gcPath="$nixStateDir/gcroots/per-user/$USER"
 
     declare -gr nixProfilePath="$profilesPath/profile"
     declare -gr genProfilePath="$profilesPath/home-manager"
```

The issue of the topic seems to be fixed, but I am not sure about the implications yet. Also this is not sufficient to make Home-Manager to work with store inside `$HOME/.local/share/nix` because the symlinks inside the home still assumes that everything is coming from `/nix/store`, so something else needs to be changed inside the code.

**Comment by rycee** [comment] 2023-03-07 22:40
@thiagokokada Thanks for the description.

If anybody could try out #3742 that would be great. It seems to work OK for me in a fresh Debian VM with Nix 2.14.1 but it would be good to have extra confirmation.

**Comment by rycee** [comment] 2023-03-07 23:02
@cvoges12 The stable version of Nix is still 2.13 at the moment so NixOS users should be safe.

IMHO 2.13 should stay as stable until the interaction with `nix-collect-garbage` is sorted out (as far as I can tell `nix-collect-garbage` will not expire profiles at the new profile location). Ideally also documentation updates (this pretty major change is not even mentioned in the release notes, unless I'm mistaken).

**Comment by cvoges12** [comment] 2023-03-07 23:25
No bitterness inferred heh. I like to be very direct as well.

I still think unstable should be prioritized. But yes, I agree that such a major change should be put in the release notes.

Anyways, I've cloned the branch that you've made. But I'm not seeing where in the contributing section of the manual on how to build it without `home-manager` already installed. It seems that section 5.1 assumes home-manager has already been successfully installed. I tried building the flake via:
```sh
nix build --no-link path:<path>/home-manager
"$(nix path-info path:<path>/home-manager)"/activate
```
Which gave an error: `<shell>: /nix/store/<hash>-home-manager/activate: No such file or directory`

I might be wrong in how I'm attempting this, but I do know that at least `/nix/store/<hash>-home-manager` does exist with a bin and share directory.

**Comment by jskulski** [comment] 2023-03-08 06:11
@rycee works with `test-install` 👍 

I had a raspberry pi running Raspbian/Debian 11 that failed finding the lock file. Google searches led me here. 

```shell
jsk@fieldagent:~ $ nix --version
nix (Nix) 2.14.0
jsk@fieldagent:~ $ ls -l .nix*
-rw-r--r-- 1 jsk jsk  133 Mar  2 23:55 .nix-channels
lrwxrwxrwx 1 jsk jsk   43 Feb 28 18:20 .nix-profile -> /home/jsk/.local/state/nix/profiles/profile
``` 

I ran `make test-install` on a fresh clone of the repo. 

On `master` `test-install` failed finding the lock file as expected.

```
building '/nix/store/25x60nr8kn99jrhajn81gdnnl5kih69x-activation-script.drv'...
building '/nix/store/0rswr5gllp8g4niyg4sbplp6kwbjfsfs-home-manager-generation.drv'...
/nix/store/25d890qaafdi6npj75kdj4c1107xw35l-home-manager-generation
/nix/store/fz80arp0cldc6lprk1z11g3d62vpmj78-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Starting Home Manager activation
error: opening lock file '/nix/var/nix/profiles/per-user/jsk/home-manager.lock': No such file or directory
Uh oh, the installation failed! Please create an issue at

    https://github.com/nix-community/home-manager/issues

if the error seems to be the fault of Home Manager.
make: *** [Makefile:17: test-install] Error 1

jsk@fieldagent:~/Code/github/nix-community/home-manager $ git branch
* master
  migrate-profiles-and-gcroot
```

And `make test-install` on the `migrate-profiles-and-gcroot` branch:

```
installing 'home-manager-path'
building '/nix/store/q572n1dx7v725vr0c7im1194cqnrw0ya-user-environment.drv'...
Activating linkGeneration
Creating profile generation 1
Creating home file links in /tmp/tmp.oQeM5040Vn
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Activating onFilesChange
Activating reloadSystemd
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

There are 84 unread and relevant news items.
Read them by running the command "home-manager news".

All done! The home-manager tool should now be installed and you can edit

    /tmp/tmp.oQeM5040Vn/.config/nixpkgs/home.nix

to configure Home Manager. Run 'man home-configuration.nix' to
see all available options.

jsk@fieldagent:~/Code/github/nix-community/home-manager $ git branch
  master
* migrate-profiles-and-gcroot
```

I haven't installed it fully on my system yet because well I haven't figured it out yet, but let me know if you need any more info

**Comment by jskulski** [comment] 2023-03-08 06:14
@rycee #3742 works with `test-install` 👍 

I had a raspberry pi running Raspbian/Debian 11 that failed finding the lock file. Google searches led me here. 

```shell
jsk@fieldagent:~ $ nix --version
nix (Nix) 2.14.0
jsk@fieldagent:~ $ ls -l .nix*
-rw-r--r-- 1 jsk jsk  133 Mar  2 23:55 .nix-channels
lrwxrwxrwx 1 jsk jsk   43 Feb 28 18:20 .nix-profile -> /home/jsk/.local/state/nix/profiles/profile
``` 

I ran `make test-install` on a fresh clone of the repo. 

On `master` `test-install` failed finding the lock file as expected.

```
building '/nix/store/25x60nr8kn99jrhajn81gdnnl5kih69x-activation-script.drv'...
building '/nix/store/0rswr5gllp8g4niyg4sbplp6kwbjfsfs-home-manager-generation.drv'...
/nix/store/25d890qaafdi6npj75kdj4c1107xw35l-home-manager-generation
/nix/store/fz80arp0cldc6lprk1z11g3d62vpmj78-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Starting Home Manager activation
error: opening lock file '/nix/var/nix/profiles/per-user/jsk/home-manager.lock': No such file or directory
Uh oh, the installation failed! Please create an issue at

    https://github.com/nix-community/home-manager/issues

if the error seems to be the fault of Home Manager.
make: *** [Makefile:17: test-install] Error 1

jsk@fieldagent:~/Code/github/nix-community/home-manager $ git branch
* master
  migrate-profiles-and-gcroot
```

And `make test-install` on the `migrate-profiles-and-gcroot` branch:

```
installing 'home-manager-path'
building '/nix/store/q572n1dx7v725vr0c7im1194cqnrw0ya-user-environment.drv'...
Activating linkGeneration
Creating profile generation 1
Creating home file links in /tmp/tmp.oQeM5040Vn
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Activating onFilesChange
Activating reloadSystemd
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

There are 84 unread and relevant news items.
Read them by running the command "home-manager news".

All done! The home-manager tool should now be installed and you can edit

    /tmp/tmp.oQeM5040Vn/.config/nixpkgs/home.nix

to configure Home Manager. Run 'man home-configuration.nix' to
see all available options.

jsk@fieldagent:~/Code/github/nix-community/home-manager $ git branch
  master
* migrate-profiles-and-gcroot
```

I haven't installed it fully on my system yet because well I haven't figured it out yet, but let me know if you need any more info

**Comment by rycee** [comment] 2023-03-08 07:27
@jskulski Hmm, it may be that you got an older commit. I think the readonly variable issues should be resolved in the latest version.

I merged the PR to master so now it should be possible to test just by updating HM in the regular way.

**Comment by jskulski** [comment] 2023-03-08 08:28
Thanks, installed and everything working as expected for me.

**Comment by rycee** [comment] 2023-03-08 08:32
@jskulski Great to hear! Thanks for trying out and reporting on the result.

I'll close this issue for now, if anybody encounters the same issue after updating please write a comment.

**Closed by rycee** 2023-03-08 08:32 UTC
Labels: bug

**Comment by Lindenk** [comment] 2023-05-03 02:55
I seem to be having the same issue, also on Arch Linux. My `.nix-profile` points to `/home/lindenk/.local/state/nix/profiles/profile`, and `nix-env` works using it, however home-manager specifically tries to lock `/nix/var/nix/profiles/per-user/lindenk/home-manager.lock` which does not exist. Creating the directories manually causes `Permission denied`. This is also an issue using both the latest `unstable` (23.05-pre) and `github:nix-community/home-manager/release-22.11`

**Comment by ulysses4ever** [comment] 2023-05-07 15:17
> For reference I'm trying to create dotfiles with a nix flake, with pretty much the same template [as this](https://nix-community.github.io/home-manager/index.html#ch-nix-flakes). Running home-manager switch --flake '.#lindenk' causes the issue

I'm trying the same and running into this issue on Ubuntu 20.04. I (re)installed `nix` yesterday using the `sh`-based command from the website. And I have the same permission denied failure. The `profiles` directory does exist.

```console
> nix run home-manager/master -- --flake ~/dotfiles/hm-only switch
error: opening lock file '/nix/var/nix/profiles/per-user/artem/home-manager.lock': Permission denied

> ll /nix/var/nix/profiles/per-user/artem
lrwxrwxrwx 15 root  6 May 16:39 channels -> channels-4-link
lrwxrwxrwx 60 root 11 Dec  2020 channels-2-link -> /nix/store/qni5gy8rjjyw3vpqh0ij10mq6h52x206-user-environment
lrwxrwxrwx 60 root  8 Oct  2021 channels-3-link -> /nix/store/95wnq250bhn6jk73ivd67s6dh2l3v85g-user-environment
lrwxrwxrwx 60 root  6 May 16:39 channels-4-link -> /nix/store/7ibvmbxqls2310lkflls4ibxrpwk84ms-user-environment
lrwxrwxrwx 14 root  6 May 16:41 profile -> profile-2-link
lrwxrwxrwx 60 root 27 Apr  2020 profile-1-link -> /nix/store/04z1n36fhpdr0fayp2s2v3fp3njvsr79-user-environment
lrwxrwxrwx 60 root  6 May 16:41 profile-2-link -> /nix/store/j8dis32qf9hmfbgg1gb58iz8ara328q6-user-environment
```

Could someone help me figuring what to do about it? Should I provide more info? My config (including the `hm-only` config mentioned above) is on the branch here: https://github.com/ulysses4ever/dotfiles/tree/prl-julia. Here's `nix-info`:

```console
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-122-generic, Ubuntu, 20.04.4 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(artem): `"nixpkgs-23.05pre481435.caf436a52b2"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/artem/.nix-defexpr/channels/nixpkgs`
```

**Comment by PassiveLemon** [comment] 2023-06-15 03:14
I get a seemingly similar or related issue: `error: opening lock file '/home/lemon/.local/state/nix/profiles/home-manager.lock': Permission denied`

It used to work fine when I was on 22.11 but I decided to reinstall with 23.05 when switching to a new NVME and now I can't finish setting up

**Comment by nuttycom** [comment] 2023-07-04 15:05
I just ran into this again on a fresh `nix` install using version 2.16.1.

**Comment by ethanabrooks** [comment] 2023-07-19 21:04
I am also having this issue. Same setup as @nuttycom. Please reopen.

**Comment by emagdel** [comment] 2023-09-06 08:34
> I'm on a Kali linux host, and I could solve this issue by doing:
> 
> ```
> mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
> ```

Similarly, the following worked for me: `sudo chown -R $USER:nixbld /nix/var/nix/profiles/per-user/$USER`

**Comment by coolcorexix** [comment] 2023-11-07 03:05
> > I'm on a Kali linux host, and I could solve this issue by doing:
> > ```
> > mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
> > ```
> 
> Similarly, the following worked for me: `sudo chown -R $USER:nixbld /nix/var/nix/profiles/per-user/$USER`

this work like a charm, thank you

**Comment by jjant** [comment] 2024-02-09 12:07
Just ran into this problem with a fresh Mac.

System information:
```
OS: macOS Sonoma 14.3
Nix: nix (Nix) 2.20.1
HomeManager: 24.05-pre
```

I had to do both:

```bash
mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
sudo chown -R $USER:nixbld /nix/var/nix/{profiles,gcroots}/per-user/$USER
```

to get HM switch to work.

**Comment by drupol** [comment] 2024-05-03 09:01
On Ubuntu:

```
sudo mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
sudo chown -R $USER:nixbld /nix/var/nix/{profiles,gcroots}/per-user/$USER
```

Worked perfectly. I wonder why we have to do that... UX wise it's very repellent.

**Comment by drupol** [comment] 2025-04-16 05:26
> I just got this error with a freshly installing NixOS (but keeping the old home). Turns out in fact no command worked, like: `nix profile install nixpkgs#hello` would return an error `error: filesystem error: directory iterator cannot open directory: No such file or directory [/nix/var/nix/profiles/per-user/me]`. This is actually related to https://github.com/DeterminateSystems/nix-installer/issues/477: simply running:
> ```
> $ rm ~/.nix-profile
> ```
> would solve my issue (in non-NixOS system, someone recommended to also source some file, not needed for me)
> 
> Then, I could run `LANG=C nix run nixpkgs#home-manager -- switch` as usual!

How come this is related to Determined System when using NixOS ? I am confused.

**Comment by tobiasBora** [comment] 2025-04-16 08:20
@drupol First I did not realized it was on determined system, thought it was simply in nix's repo. But I still think it might be related, in the sense that it may be a bug in nix itself, that percolate to other tools, including determinate system (but I don't know anything about Determinate System, so I may be wrong here). At least the same error message and same solution apply!

**Comment by drupol** [comment] 2025-04-16 08:46
But Nixos uses Nix, it doesn't use any determined system's artefacts.... So I'm as confused as before by your message.

**Comment by tobiasBora** [comment] 2025-04-16 09:02
@drupol NixOs uses nix, DS uses nix, home-manager uses nix… So I don't see why it would be absurd that a nix bug appears in NixOS, DS and home-manager, especially when the error & solution is exactly the same in all cases. But if makes no sense to you, just ignore my comment, but I'm still curious to understand why I got that error… My bet is that it is because of a nix-related bug, but you can have other (certainly more educated) guesses…

**Comment by drupol** [comment] 2025-04-16 09:17
No worries at all, I can still sleep soundly even if I don’t fully understand it :) There’s so much in the Nix ecosystem that I’m still wrapping my head around...or at least trying to!

What I was trying to point out earlier is that your initial message was a bit confusing because it described an issue you encountered on NixOS, but linked to an issue from Determined Systems. That kind of linking might give the impression that the two projects are closely related, even though they’re actually **quite separate**. On top of that, DS has been fairly controversial lately, so referencing one of their issues might distract from the actual root cause. Perhaps linking to something directly from the Nix project would have made things clearer.

Anyway, thanks for sharing your experience, it is always helpful to see how others tackle these kinds of quirks!
