### ISSUE TITLE
bug: Himalaya 0.8.0 has breaking config changes

### ISSUE THREAD

**Issue by jalil-salame** [nix-community/home-manager#4092] opened 2023-06-14 19:15 UTC
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The new config changes `imap-password-cmd = "..."` to `imap-auth = "passwd"` and `imap-passwd = { cmd = "..." }`, as stated [here](https://pimalaya.org/himalaya/cli/configuration/gmail.html).

This means that `himalaya` is broken when using with `nixos-unstable`

### Maintainer CC

@soywod @toastal 

### System information

```console
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.11 (Tapir), 23.11.20230612.0eeebd6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

I am using flakes so the relevant `nix flake metadata`:
```
├───home-manager: github:nix-community/home-manager/75b24cc557d4947ab46691142863e5a5db5c3f78
│   └───nixpkgs follows input 'nixpkgs'
├───nixpkgs: github:NixOS/nixpkgs/0eeebd64de89e4163f4d3cf34ffe925a5cf67a05
```

**Comment by soywod** [comment] 2023-06-14 19:46
We were faster than me :smile: my PR was waiting locally for Himalaya v0.8.0 to be merged on nixpkgs, I just opened it: https://github.com/nix-community/home-manager/pull/4093

**Comment by soywod** [comment] 2023-06-21 19:10
The PR has been merged, so the issue is technically fixed and can be closed.

**Closed** 2023-06-21 19:16 UTC
Labels: bug, triage
