### ISSUE TITLE
bug: Fails to build with nixpkgs unstable

### ISSUE THREAD

**Issue by ryanbooker** [nix-community/home-manager#4147] opened 2023-06-23 04:00 UTC
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Seems similar to https://github.com/nix-community/home-manager/issues/3344

I'm using nix-darwin/home-manager. Please let me know if more information is needed.

```
error: builder for '/nix/store/n0ax7640wkz4cq7rlz75yxaxij0wirfz-manual-combined.drv' failed with exit code 3;
       last 10 log lines:
       > /nix/store/jkar4sfq1md6vbbgy3cg0l858xa24qlf-manual-combined/manual-combined.xml:1504: element listitem: Relax-NG validity error : Did not expect element listitem there
       >   1500        not bound to an attribute.</simpara>
       >   1501    <simpara>Some arguments are already passed by default, of which the
       >   1502     following <emphasis>cannot</emphasis> be changed with this option:</simpara>
       >   1503    <itemizedlist>
       >   1504  <listitem><para><simpara><varname>lib</varname>: The nixpkgs library.</simpara>
       >   1505 </para></listitem>
       >   1506      <listitem><para><simpara><varname>config</varname>: The results of all options after merging the values from all modules together.</simpara>
       >
       > /nix/store/jkar4sfq1md6vbbgy3cg0l858xa24qlf-manual-combined/manual-combined.xml fails to validate
       For full logs, run 'nix log /nix/store/n0ax7640wkz4cq7rlz75yxaxij0wirfz-manual-combined.drv'.
```

### System information

```markdown
- system: `"aarch64-darwin"`
 - host os: `Darwin 23.0.0, macOS 14.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by ncfavier** [comment] 2023-06-23 09:02
Looks like a duplicate of https://github.com/nix-community/home-manager/issues/4142, which is the most recent instance.

**Closed by ncfavier** 2023-06-23 09:02 UTC
Labels: bug, triage

**Comment by ryanbooker** [comment] 2023-06-24 02:31
It does. Thanks. I missed that one.
