### ISSUE TITLE
Showing home-manager log when using as NixOS module...?

### ISSUE THREAD

**Issue by VergeDX** [nix-community/home-manager#2672] opened 2022-01-29 01:48 UTC
### Description
When using home-manager as NixOS module, I noticed the pretty hm logs is missing.
Unfortunately, I'm using "/ on tmpfs" pattern, and I'm not finding a way to use hm alone.

I know the hm log will print in journal, I can add an `system.activationScripts` step back.
But this way is hacky, and missing pretty color output : (

**Comment by mainrs** [comment] 2022-02-02 20:06
Would you mind sharing the script that re-enables hm logs?

**Comment by berbiche** [comment] 2022-05-10 23:47
Didn't realize this was a duplicate of #2464.

Closing.

**Closed by berbiche** 2022-05-10 23:47 UTC
Labels: feature request, pinned
