### ISSUE TITLE
flakes + neovim.extraconfig

### ISSUE THREAD

**Issue by theduke** [nix-community/home-manager#1798] opened 2021-02-15 00:19 UTC
### Issue description

The following config used with `flakes` produces an error:

```nix
programs.neovim = {
  enable = true;
  ...
  extraConfig = builtins.readFile ../../config/nvim/init.vim
};
```

```
error: --- RestrictedPathError ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
access to path '/nix/store/config/nvim/init.vim' is forbidden in restricted mode
```

**Comment by theduke** [comment] 2021-02-15 00:23
Ah, I noticed just now that it works fine if the config is inside the flake directory, eg `extraConfig = builtins.readFile ./config/nvim/init.vim`.

Apparently the file can not be outside of the flake dir.

Maybe there could be some explicit check here with a better error message?

The same concern applies to `home.file.*` configuration.

**Comment by thiagokokada** [comment] 2021-02-15 01:56
This is a general restriction of Flakes, not only for Home Manager (you can't access any file outside the git repository, unless if you use `--impure` flag, since this would make the Flake non-reproducible).

So I don't  think it makes much sense to document this in HM. Maybe in a more general Flake documentation :thinking: ?

**Comment by theduke** [comment] 2021-02-15 02:03
`home-manager` might well be the first point of contact with flakes for many Nix users, as it is for me. 

I reckon the extra line in the README can't hurt if it saves others some time, especially since including config files is probably pretty common for home-manager.

**Comment by teto** [comment] 2021-02-27 16:45
Problem solved (not a HM one): closing.

**Closed by teto** 2021-02-27 16:45 UTC
Labels: program: neovim
