### ISSUE TITLE
Assertion `request.expectedETag == res.etag' failed.

### ISSUE THREAD

**Issue by AusCyberman** [nix-community/home-manager#1742] opened 2021-01-22 13:12 UTC
i just tried to `home-manager-switch` when this happened
```
nix-build: src/libfetchers/tarball.cc:67: nix::fetchers::DownloadFileResult nix::fetchers::downloadFile(nix::ref<nix::Store>, const string&, const string&, bool, const Headers&): Assertion `request.expectedETag == res.etag' failed.
/home/auscyber/.nix-profile/bin/home-manager: line 99:  5270 Aborted                 (core dumped) nix-build "<home-manager/home-manager/home-manager.nix>" "${extraArgs[@]}" "${PASSTHROUGH_OPTS[@]}" --argstr confPath "$HOME_MANAGER_CONFIG" --argstr confAttr "$HOME_MANAGER_CONFIG_ATTRIBUTE"

There are 5 unread and relevant news items.
Read them by running the command 'home-manager news'.

```

I'm on nixos-unstable and home-manager master

i have tried rolling back, nixos-rebuild and `nix-channel --update`

**Comment by cole-h** [comment] 2021-01-22 18:29
Related to https://github.com/NixOS/nix/issues/4469.

**Comment by rycee** [comment] 2021-01-22 19:27
Indeed, I can't imagine this problem is caused by HM or that HM can work around it.

**Comment by berbiche** [comment] 2021-01-22 20:00
Closing this, please reopen if needed.

**Closed by berbiche** 2021-01-22 20:00 UTC
