### ISSUE TITLE
bug: programs.ssh.matchBlocks doesn't support all options listed in ssh_config(5)

### ISSUE THREAD

**Issue by haizaar** [nix-community/home-manager#4358] opened 2023-08-18 05:22 UTC
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

It looks like the [list](https://github.com/nix-community/home-manager/blob/master/modules/programs/ssh.nix#L66) of `matchBlocks` options is out of sync with what openssh currently supports. For example `IdentityAgent`, `StreamLocalBindUnlink` are not supported, resulting in convoluted configurations like:

```nix
{
  ...
  programs.ssh = {
   ...
    matchBlocks = {
      "github.com" = {
        hostname = "github.com";
        user = "git";
        extraOptions = {
          IdentityAgent = "~/.1password/agent.sock";
        };
};
```

Can we please have ssh module extended to support the full list of what openssh supports?

### Maintainer CC

@rycee 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.45, NixOS, 23.05 (Stoat), 23.05.2835.b30c68669df7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment] 2023-08-18 09:01
Duplicate of https://github.com/nix-community/home-manager/issues/4134

**Closed by ncfavier** 2023-08-18 09:01 UTC
Labels: bug, triage
