### ISSUE TITLE
systemwide install NIX_PATH error

### ISSUE THREAD

**Issue by bb2020** [nix-community/home-manager#4060] opened 2023-06-04 19:08 UTC
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I was using home-manager on NixOS as system wide installed with `environment.systemPackages`.
Today I've updated to 23.05 and `home-manager switch` started to return this error:
`error: file 'home-manager/home-manager/home-manager.nix' was not found in the Nix search path (add it using $NIX_PATH or -I)
at «none»:0: (source not available)`

Is this a bug or using home-manager without adding the channel is not supported anymore?

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.533.c37ca420157`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Bujiraso** [comment] 2023-06-08 17:31
I have also seen this same 'home-manager/home-manager/home-manager.nix' on another PC recently.
Is three levels of depth expected or is this indicative of some fault?

**Comment by piegamesde** [comment] 2023-06-17 13:32
Given that it used to work prior to the update I'd say this is a regression and not user error. This prevents me from installing packages or otherwise changing my home configuration, so a workaround would be appreciated.

**Comment by bb2020** [comment] 2023-06-17 13:37
I agree. I don't want to add home-manager channel when I am already using NixOS.

**Comment by piegamesde** [comment] 2023-06-19 13:45
Note that this also happens on a non-NixOS install. I think adding a home-manager channel like described in the installation instructions would work around the issue.

However it previously worked without requiring a channel, and I'd prefer relying on channels as little as possible. I'd be curious to know how it used to work before it broke, because I have no idea.

**Comment by uzytkownik** [comment] 2023-06-21 03:19
Following installation instruction seems to break NixOS for me:

```
# nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
# nixos-rebuild switch --upgrade
error: reading symbolic link '/nix/var/nix/profiles/per-user/root/channels/home-manager': No such file or directory
nixos-rebuild failed with exit status 1.
```

**Comment by bb2020** [comment] 2023-06-25 15:38
I installed an older version of `home-manager` into my user environment, such as:
`nix-env -iA home-manager -f https://github.com/NixOS/nixpkgs/archive/8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8.tar.gz`

However this can only be a temporary solution :disappointed:

**Comment by eclairevoyant** [comment] 2023-06-25 19:43
@piegamesde Step 2 of [the installation instructions](https://nix-community.github.io/home-manager/index.html#sec-install-standalone) tells you to add a channel, this seems like user error.

@uzytkownik Why would you add the channel as root for a standalone installation?

**Comment by piegamesde** [comment] 2023-08-04 16:14
This is an upstream Nixpkgs issue, and should probably be closed in favor of https://github.com/NixOS/nixpkgs/issues/236940.

As a workaround, the following override fixes home-manager for me:

```nix
    (home-manager.overrideAttrs (old: {
      installPhase = builtins.replaceStrings [ ''--subst-var-by HOME_MANAGER_PATH "" \'' ] [ ''--subst-var-by HOME_MANAGER_PATH '${old.src}' \'' ] old.installPhase;
    }))
```

**Closed** 2023-08-04 16:58 UTC
Labels: bug, triage
