### ISSUE TITLE
manage programs with homemanager that are not installed with nix

### ISSUE THREAD

**Issue by tnxz** [nix-community/home-manager#4338] opened 2023-08-13 04:17 UTC
### Description

so the main use case is on macos where i need to configure gui apps like vscode, brave, intellij-idea which are installed with homebrew casks.

so is there a work around to get this working

**Comment by eclairevoyant** [comment] 2023-08-13 18:17
Duplicate of #3375.

**Closed** 2023-08-13 18:19 UTC
Labels: feature request
